// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "rs-categories": {
    "label"?: string;
    "title"?: string;
  };
  "rs-editorial": {
    "subtitle"?: string;
    "title"?: string;
    "image_main"?: string;
    "side_title"?: string;
    "body"?: string;
    "image_side"?: string;
    "cta_text"?: string;
    "cta_url"?: string;
  };
  "rs-featured": {
    "label"?: string;
    "title"?: string;
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
  };
  "rs-hero": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "rs-image-with-text": {
    "label"?: string;
    "headline"?: string;
    "headline_accent"?: string;
    "text"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
    "image_alt"?: string;
    "image_position"?: "left" | "right";
  };
  "rs-marquee": {
    "repeat"?: number;
  };
  "rs-newsletter": {
    "subtitle"?: string;
    "placeholder"?: string;
    "success_text"?: string;
  };
  "rs-order-confirmation-section": {
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "show_emoji"?: boolean;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
  };
  "rs-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "rs-products-page": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "rs-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "rs-promo-banner": {
    "journal_label"?: string;
    "journal_title"?: string;
    "journal_link"?: string;
    "edit_label"?: string;
    "edit_text"?: string;
    "edit_link"?: string;
    "cta_text"?: string;
    "product_image"?: string;
  };
}
