"""Core exceptions module."""

from src.core.exceptions.base import (
    AccountLockedError,
    AuthenticationError,
    AuthorizationError,
    BusinessRuleViolationError,
    DomainException,
    EntityAlreadyExistsError,
    EntityNotFoundError,
    ExternalServiceError,
    FeatureDisabledError,
    FeatureNotAvailableError,
    FeatureNotReleasedError,
    InsufficientStockError,
    InvalidCredentialsError,
    InvalidTokenError,
    PaymentError,
    PlanLimitExceededError,
    TokenExpiredError,
    ValidationError,
)

__all__ = [
    "DomainException",
    "EntityNotFoundError",
    "EntityAlreadyExistsError",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "BusinessRuleViolationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "InvalidTokenError",
    "AccountLockedError",
    "InsufficientStockError",
    "PaymentError",
    "PlanLimitExceededError",
    "FeatureNotAvailableError",
    "FeatureDisabledError",
    "FeatureNotReleasedError",
    "ExternalServiceError",
]
