// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "ed-categories": {
    "title"?: string;
    "max_items"?: number;
  };
  "ed-featured-collection": {
    "title"?: string;
    "collection_tag"?: "new" | "bestseller" | "featured";
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "ed-hero": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "hero_image_url"?: string;
  };
  "ed-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "ed-order-confirmation-section": {
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "show_emoji"?: boolean;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
  };
  "ed-product-detail-section": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "ed-products-page-section": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "ed-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "ed-promo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
  };
  "ed-testimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
