// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "elegant-categories": {
    "title"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
  };
  "elegant-collection-strip": {
    "title"?: string;
    "layout"?: "image-row" | "text-strip";
    "item_1_image"?: string;
    "item_1_label"?: string;
    "item_1_link"?: string;
    "item_2_image"?: string;
    "item_2_label"?: string;
    "item_2_link"?: string;
    "item_3_image"?: string;
    "item_3_label"?: string;
    "item_3_link"?: string;
    "item_4_image"?: string;
    "item_4_label"?: string;
    "item_4_link"?: string;
  };
  "elegant-featured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "product_ids"?: string;
    "collection_tag"?: "new" | "bestseller" | "featured" | "sale";
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "elegant-hero": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "hero_image_url"?: string;
  };
  "elegant-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "elegant-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "elegant-products-page": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "elegant-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "elegant-promo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
  };
  "elegant-testimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
