"""Theme section schemas for the v2 section engine.

These schemas mirror the storefront's section/schema.json files.
The dashboard uses them to dynamically generate editor UIs.
Phase 5 will automate syncing from the storefront build output.
"""

from typing import Any

# ── Section schemas (shared across all themes) ──────────────────────────────

SECTION_SCHEMAS: list[dict[str, Any]] = [
    {
        "type": "hero",
        "name": "Hero Banner",
        "nameAr": "البانر الرئيسي",
        "limit": 1,
        "settings": [
            {
                "key": "badge_text",
                "type": "text",
                "label": "Badge Text",
                "labelAr": "نص الشارة",
                "default": "🎉 خصومات تصل لـ ٢٥٪",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "headline",
                "type": "text",
                "label": "Headline",
                "labelAr": "العنوان الرئيسي",
                "default": "اكتشف أحلى المنتجات بأفضل الأسعار",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "textarea",
                "label": "Subtitle",
                "labelAr": "العنوان الفرعي",
                "default": "تشكيلة مميزة من الملابس والإكسسوارات بتوصيل لكل مصر. جودة عالية وأسعار مناسبة.",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_text",
                "type": "text",
                "label": "Primary Button Text",
                "labelAr": "نص الزر الرئيسي",
                "default": "تسوق الآن",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_link",
                "type": "url",
                "label": "Primary Button Link",
                "labelAr": "رابط الزر الرئيسي",
                "default": "/products",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "secondary_text",
                "type": "text",
                "label": "Secondary Button Text",
                "labelAr": "نص الزر الثانوي",
                "default": "الملابس الجديدة",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "secondary_link",
                "type": "url",
                "label": "Secondary Button Link",
                "labelAr": "رابط الزر الثانوي",
                "default": "/products?category=clothing",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "hero_image_url",
                "type": "image",
                "label": "Hero Image (Main)",
                "labelAr": "الصورة الرئيسية",
                "default": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                "group": "Media",
                "groupAr": "الوسائط",
            },
            {
                "key": "hero_image_2",
                "type": "image",
                "label": "Hero Image 2",
                "labelAr": "صورة ٢",
                "default": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
                "group": "Media",
                "groupAr": "الوسائط",
            },
            {
                "key": "hero_image_3",
                "type": "image",
                "label": "Hero Image 3",
                "labelAr": "صورة ٣",
                "default": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
                "group": "Media",
                "groupAr": "الوسائط",
            },
            {
                "key": "hero_image_4",
                "type": "image",
                "label": "Hero Image 4",
                "labelAr": "صورة ٤",
                "default": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
                "group": "Media",
                "groupAr": "الوسائط",
            },
            {
                "key": "show_trust_strip",
                "type": "checkbox",
                "label": "Show Trust Strip (Mobile)",
                "labelAr": "إظهار شريط الثقة",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [
            {
                "name": "Hero Banner",
                "nameAr": "بانر رئيسي",
                "category": "Hero",
                "categoryAr": "بطل",
                "settings": {
                    "headline": "اكتشف أحلى المنتجات بأفضل الأسعار",
                    "cta_text": "تسوق الآن",
                    "cta_link": "/products",
                },
            },
        ],
    },
    {
        "type": "categories",
        "name": "Category Grid",
        "nameAr": "شبكة الفئات",
        "limit": 1,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Section Title",
                "labelAr": "عنوان القسم",
                "default": "تسوق حسب الفئة",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "columns_desktop",
                "type": "range",
                "label": "Columns (Desktop)",
                "labelAr": "أعمدة (ديسكتوب)",
                "default": 5,
                "min": 3,
                "max": 6,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "columns_mobile",
                "type": "range",
                "label": "Columns (Mobile)",
                "labelAr": "أعمدة (موبايل)",
                "default": 3,
                "min": 2,
                "max": 4,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "max_items",
                "type": "range",
                "label": "Max Categories",
                "labelAr": "أقصى عدد فئات",
                "default": 0,
                "min": 0,
                "max": 12,
                "step": 1,
                "description": "0 = show all",
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [
            {
                "name": "Category Grid",
                "nameAr": "شبكة الفئات",
                "category": "Collection",
                "categoryAr": "تصنيف",
            },
        ],
    },
    {
        "type": "featured-collection",
        "name": "Featured Collection",
        "nameAr": "مجموعة مميزة",
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "وصل حديثاً ✨",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "text",
                "label": "Subtitle",
                "labelAr": "عنوان فرعي",
                "default": "أحدث المنتجات اللي ضفناها",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "product_ids",
                "type": "products",
                "label": "Pick products (manual)",
                "labelAr": "اختيار المنتجات",
                "default": [],
                "help": (
                    "When you pick products here, they are used in the order "
                    "selected. Leave empty to auto-fill from the collection below."
                ),
                "helpAr": (
                    "عند اختيار منتجات هنا، يتم استخدامها بالترتيب. اترك الحقل "
                    "فارغاً للتعبئة التلقائية من المجموعة أدناه."
                ),
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "collection_tag",
                "type": "select",
                "label": "Collection (auto-fill)",
                "labelAr": "المجموعة (تعبئة تلقائية)",
                "default": "new",
                "options": [
                    {"label": "New Arrivals", "labelAr": "وصل حديثاً", "value": "new"},
                    {
                        "label": "Best Sellers",
                        "labelAr": "الأكثر مبيعاً",
                        "value": "bestseller",
                    },
                    {"label": "Featured", "labelAr": "مميز", "value": "featured"},
                    {"label": "Sale", "labelAr": "تخفيضات", "value": "sale"},
                ],
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "view_all_text",
                "type": "text",
                "label": "View All Text",
                "labelAr": "نص عرض الكل",
                "default": "عرض الكل",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "view_all_link",
                "type": "url",
                "label": "View All Link",
                "labelAr": "رابط عرض الكل",
                "default": "/products",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "product_count",
                "type": "range",
                "label": "Products to Show",
                "labelAr": "عدد المنتجات",
                "default": 4,
                "min": 2,
                "max": 8,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "columns",
                "type": "range",
                "label": "Columns (Desktop)",
                "labelAr": "أعمدة (ديسكتوب)",
                "default": 4,
                "min": 2,
                "max": 5,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [
            {
                "name": "New Arrivals",
                "nameAr": "وصل حديثاً",
                "category": "Collection",
                "categoryAr": "تصنيف",
                "settings": {
                    "title": "وصل حديثاً ✨",
                    "subtitle": "أحدث المنتجات اللي ضفناها",
                    "collection_tag": "new",
                    "view_all_link": "/products?tag=new",
                },
            },
            {
                "name": "Best Sellers",
                "nameAr": "الأكثر مبيعاً",
                "category": "Collection",
                "categoryAr": "تصنيف",
                "settings": {
                    "title": "الأكثر مبيعاً 🔥",
                    "subtitle": "المنتجات اللي الناس بتحبها",
                    "collection_tag": "bestseller",
                    "view_all_link": "/products?tag=bestseller",
                },
            },
        ],
    },
    {
        "type": "promo-banner",
        "name": "Promotional Banner",
        "nameAr": "بانر ترويجي",
        "settings": [
            {
                "key": "badge_text",
                "type": "text",
                "label": "Badge Text",
                "labelAr": "نص الشارة",
                "default": "عرض محدود 🔥",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "headline",
                "type": "text",
                "label": "Headline",
                "labelAr": "العنوان",
                "default": "خصم ٢٥٪ على كل الإكسسوارات",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "text",
                "label": "Subtitle",
                "labelAr": "عنوان فرعي",
                "default": "العرض ساري لنهاية الشهر. متفوتش الفرصة!",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_text",
                "type": "text",
                "label": "Button Text",
                "labelAr": "نص الزر",
                "default": "تسوق الإكسسوارات",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_link",
                "type": "url",
                "label": "Button Link",
                "labelAr": "رابط الزر",
                "default": "/products?category=accessories",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "image_url",
                "type": "image",
                "label": "Image",
                "labelAr": "الصورة",
                "default": "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=400",
                "group": "Media",
                "groupAr": "الوسائط",
            },
            {
                "key": "diagonal_text",
                "type": "text",
                "label": "Diagonal Banner Text",
                "labelAr": "نص البانر المائل",
                "default": "",
                "description": "Optional text for diagonal ribbon overlay",
                "group": "Content",
                "groupAr": "المحتوى",
            },
        ],
        "presets": [
            {
                "name": "Promo Banner",
                "nameAr": "بانر ترويجي",
                "category": "Promotional",
                "categoryAr": "ترويجي",
            },
        ],
    },
    {
        "type": "testimonials",
        "name": "Testimonials",
        "nameAr": "آراء العملاء",
        "limit": 1,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Section Title",
                "labelAr": "عنوان القسم",
                "default": "رأي عملاءنا ⭐",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "review_1_name",
                "type": "text",
                "label": "Reviewer 1 Name",
                "labelAr": "اسم المراجع ١",
                "default": "سارة أحمد",
                "group": "Review 1",
                "groupAr": "تقييم ١",
            },
            {
                "key": "review_1_city",
                "type": "text",
                "label": "Reviewer 1 City",
                "labelAr": "مدينة المراجع ١",
                "default": "القاهرة",
                "group": "Review 1",
                "groupAr": "تقييم ١",
            },
            {
                "key": "review_1_text",
                "type": "textarea",
                "label": "Review 1 Text",
                "labelAr": "نص التقييم ١",
                "default": "المنتجات جودتها ممتازة والتوصيل كان سريع جداً. هطلب تاني أكيد!",
                "group": "Review 1",
                "groupAr": "تقييم ١",
            },
            {
                "key": "review_1_rating",
                "type": "range",
                "label": "Review 1 Rating",
                "labelAr": "تقييم ١",
                "default": 5,
                "min": 1,
                "max": 5,
                "step": 1,
                "group": "Review 1",
                "groupAr": "تقييم ١",
            },
            {
                "key": "review_2_name",
                "type": "text",
                "label": "Reviewer 2 Name",
                "labelAr": "اسم المراجع ٢",
                "default": "محمد عبدالله",
                "group": "Review 2",
                "groupAr": "تقييم ٢",
            },
            {
                "key": "review_2_city",
                "type": "text",
                "label": "Reviewer 2 City",
                "labelAr": "مدينة المراجع ٢",
                "default": "الإسكندرية",
                "group": "Review 2",
                "groupAr": "تقييم ٢",
            },
            {
                "key": "review_2_text",
                "type": "textarea",
                "label": "Review 2 Text",
                "labelAr": "نص التقييم ٢",
                "default": "أول مرة أطلب أونلاين والتجربة كانت ممتازة. الخامات زي ما في الصور بالظبط.",
                "group": "Review 2",
                "groupAr": "تقييم ٢",
            },
            {
                "key": "review_2_rating",
                "type": "range",
                "label": "Review 2 Rating",
                "labelAr": "تقييم ٢",
                "default": 5,
                "min": 1,
                "max": 5,
                "step": 1,
                "group": "Review 2",
                "groupAr": "تقييم ٢",
            },
            {
                "key": "review_3_name",
                "type": "text",
                "label": "Reviewer 3 Name",
                "labelAr": "اسم المراجع ٣",
                "default": "نورهان خالد",
                "group": "Review 3",
                "groupAr": "تقييم ٣",
            },
            {
                "key": "review_3_city",
                "type": "text",
                "label": "Reviewer 3 City",
                "labelAr": "مدينة المراجع ٣",
                "default": "المنصورة",
                "group": "Review 3",
                "groupAr": "تقييم ٣",
            },
            {
                "key": "review_3_text",
                "type": "textarea",
                "label": "Review 3 Text",
                "labelAr": "نص التقييم ٣",
                "default": "أسعار حلوة والمقاسات مظبوطة. خدمة العملاء على الواتساب كانت سريعة.",
                "group": "Review 3",
                "groupAr": "تقييم ٣",
            },
            {
                "key": "review_3_rating",
                "type": "range",
                "label": "Review 3 Rating",
                "labelAr": "تقييم ٣",
                "default": 4,
                "min": 1,
                "max": 5,
                "step": 1,
                "group": "Review 3",
                "groupAr": "تقييم ٣",
            },
        ],
        "presets": [
            {
                "name": "Customer Testimonials",
                "nameAr": "آراء العملاء",
                "category": "Social Proof",
                "categoryAr": "إثبات اجتماعي",
            },
        ],
    },
    {
        "type": "newsletter",
        "name": "Newsletter Signup",
        "nameAr": "اشتراك النشرة",
        "limit": 1,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "اشترك في نشرتنا 📬",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "text",
                "label": "Subtitle",
                "labelAr": "عنوان فرعي",
                "default": "اعرف أول واحد عن العروض والمنتجات الجديدة",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "button_text",
                "type": "text",
                "label": "Button Text",
                "labelAr": "نص الزر",
                "default": "اشترك",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "placeholder",
                "type": "text",
                "label": "Placeholder",
                "labelAr": "نص العنصر النائب",
                "default": "البريد الإلكتروني",
                "group": "Content",
                "groupAr": "المحتوى",
            },
        ],
        "presets": [
            {
                "name": "Newsletter",
                "nameAr": "نشرة بريدية",
                "category": "Social Proof",
                "categoryAr": "إثبات اجتماعي",
            },
        ],
    },
    {
        "type": "marquee",
        "name": "Marquee Banner",
        "nameAr": "شريط متحرك",
        "limit": 1,
        "settings": [
            {
                "key": "text",
                "type": "text",
                "label": "Marquee Text",
                "labelAr": "نص الشريط",
                "default": "✦ خصومات حصرية ✦ شحن سريع ✦ منتجات أصلية ✦ جودة مضمونة ✦ الدفع عند الاستلام ✦",
            },
            {
                "key": "repeat_count",
                "type": "number",
                "label": "Repeat Count",
                "labelAr": "عدد التكرار",
                "default": 2,
                "min": 1,
                "max": 5,
            },
        ],
        "presets": [
            {
                "name": "Marquee Banner",
                "nameAr": "شريط متحرك",
                "category": "Promotional",
                "categoryAr": "ترويجي",
            },
        ],
    },
    {
        "type": "announcement-bar",
        "name": "Announcement Bar",
        "nameAr": "شريط الإعلانات",
        "limit": 1,
        "settings": [
            {
                "key": "text",
                "type": "text",
                "label": "Announcement Text",
                "labelAr": "نص الإعلان",
                "default": "🎉 شحن مجاني للطلبات فوق 500 جنيه",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "link_url",
                "type": "url",
                "label": "Link URL",
                "labelAr": "رابط",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "link_text",
                "type": "text",
                "label": "Link Text",
                "labelAr": "نص الرابط",
                "default": "تسوق الآن",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "dismissible",
                "type": "checkbox",
                "label": "Can be dismissed",
                "labelAr": "قابل للإغلاق",
                "default": True,
                "group": "Behavior",
                "groupAr": "السلوك",
            },
        ],
        "presets": [
            {
                "name": "Announcement Bar",
                "nameAr": "شريط إعلانات",
                "category": "Header",
                "categoryAr": "الهيدر",
            },
        ],
    },
    {
        "type": "rich-text",
        "name": "Rich Text",
        "nameAr": "نص منسق",
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "عن متجرنا",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "body",
                "type": "textarea",
                "label": "Body Text",
                "labelAr": "النص",
                "default": "نحن متجر متخصص في تقديم أفضل المنتجات بأعلى جودة وأفضل الأسعار. رضا العميل هو أولويتنا الأولى.",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "alignment",
                "type": "select",
                "label": "Text Alignment",
                "labelAr": "محاذاة النص",
                "default": "center",
                "options": [
                    {"label": "Start", "labelAr": "بداية", "value": "start"},
                    {"label": "Center", "labelAr": "وسط", "value": "center"},
                    {"label": "End", "labelAr": "نهاية", "value": "end"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "cta_text",
                "type": "text",
                "label": "Button Text",
                "labelAr": "نص الزر",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_url",
                "type": "url",
                "label": "Button URL",
                "labelAr": "رابط الزر",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "full_width_bg",
                "type": "checkbox",
                "label": "Full-width Background",
                "labelAr": "خلفية كاملة العرض",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [
            {
                "name": "Rich Text",
                "nameAr": "نص منسق",
                "category": "Content",
                "categoryAr": "محتوى",
            },
        ],
    },
    {
        "type": "image-with-text",
        "name": "Image with Text",
        "nameAr": "صورة مع نص",
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "قصتنا",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "body",
                "type": "textarea",
                "label": "Body Text",
                "labelAr": "النص",
                "default": "نسعى دائماً لتقديم أفضل المنتجات المصرية الأصيلة بجودة عالية وأسعار مناسبة.",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "image_url",
                "type": "image",
                "label": "Image",
                "labelAr": "الصورة",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "image_position",
                "type": "select",
                "label": "Image Position",
                "labelAr": "موقع الصورة",
                "default": "end",
                "options": [
                    {
                        "label": "Start (Left/Right)",
                        "labelAr": "بداية (يمين/يسار)",
                        "value": "start",
                    },
                    {
                        "label": "End (Right/Left)",
                        "labelAr": "نهاية (يسار/يمين)",
                        "value": "end",
                    },
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "cta_text",
                "type": "text",
                "label": "Button Text",
                "labelAr": "نص الزر",
                "default": "اعرف أكتر",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "cta_url",
                "type": "url",
                "label": "Button URL",
                "labelAr": "رابط الزر",
                "default": "/about",
                "group": "Content",
                "groupAr": "المحتوى",
            },
        ],
        "presets": [
            {
                "name": "Image with Text",
                "nameAr": "صورة مع نص",
                "category": "Content",
                "categoryAr": "محتوى",
            },
        ],
    },
    # ── Slideshow ──────────────────────────────────────────────────
    {
        "type": "slideshow",
        "name": "Slideshow",
        "nameAr": "عرض شرائح",
        "limit": 1,
        "settings": [
            {
                "key": "autoplay",
                "type": "checkbox",
                "label": "Autoplay",
                "labelAr": "تشغيل تلقائي",
                "default": True,
                "group": "Behavior",
                "groupAr": "السلوك",
            },
            {
                "key": "interval",
                "type": "range",
                "label": "Slide interval (seconds)",
                "labelAr": "مدة العرض (ثواني)",
                "default": 5,
                "min": 2,
                "max": 10,
                "step": 1,
                "group": "Behavior",
                "groupAr": "السلوك",
            },
            {
                "key": "height",
                "type": "select",
                "label": "Height",
                "labelAr": "الارتفاع",
                "default": "medium",
                "options": [
                    {"label": "Small", "labelAr": "صغير", "value": "small"},
                    {"label": "Medium", "labelAr": "متوسط", "value": "medium"},
                    {"label": "Large", "labelAr": "كبير", "value": "large"},
                    {"label": "Full screen", "labelAr": "ملء الشاشة", "value": "full"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "slide_1_image",
                "type": "image",
                "label": "Slide 1 image",
                "labelAr": "صورة الشريحة 1",
                "default": "",
                "group": "Slide 1",
                "groupAr": "شريحة 1",
            },
            {
                "key": "slide_1_headline",
                "type": "text",
                "label": "Slide 1 headline",
                "labelAr": "عنوان الشريحة 1",
                "default": "اكتشف تشكيلتنا الجديدة",
                "group": "Slide 1",
                "groupAr": "شريحة 1",
            },
            {
                "key": "slide_1_subtitle",
                "type": "text",
                "label": "Slide 1 subtitle",
                "labelAr": "وصف الشريحة 1",
                "default": "",
                "group": "Slide 1",
                "groupAr": "شريحة 1",
            },
            {
                "key": "slide_1_cta_text",
                "type": "text",
                "label": "Slide 1 button",
                "labelAr": "زر الشريحة 1",
                "default": "تسوق الآن",
                "group": "Slide 1",
                "groupAr": "شريحة 1",
            },
            {
                "key": "slide_1_cta_link",
                "type": "url",
                "label": "Slide 1 link",
                "labelAr": "رابط الشريحة 1",
                "default": "/products",
                "group": "Slide 1",
                "groupAr": "شريحة 1",
            },
            {
                "key": "slide_2_image",
                "type": "image",
                "label": "Slide 2 image",
                "labelAr": "صورة الشريحة 2",
                "default": "",
                "group": "Slide 2",
                "groupAr": "شريحة 2",
            },
            {
                "key": "slide_2_headline",
                "type": "text",
                "label": "Slide 2 headline",
                "labelAr": "عنوان الشريحة 2",
                "default": "",
                "group": "Slide 2",
                "groupAr": "شريحة 2",
            },
            {
                "key": "slide_2_cta_text",
                "type": "text",
                "label": "Slide 2 button",
                "labelAr": "زر الشريحة 2",
                "default": "",
                "group": "Slide 2",
                "groupAr": "شريحة 2",
            },
            {
                "key": "slide_2_cta_link",
                "type": "url",
                "label": "Slide 2 link",
                "labelAr": "رابط الشريحة 2",
                "default": "",
                "group": "Slide 2",
                "groupAr": "شريحة 2",
            },
            {
                "key": "slide_3_image",
                "type": "image",
                "label": "Slide 3 image",
                "labelAr": "صورة الشريحة 3",
                "default": "",
                "group": "Slide 3",
                "groupAr": "شريحة 3",
            },
            {
                "key": "slide_3_headline",
                "type": "text",
                "label": "Slide 3 headline",
                "labelAr": "عنوان الشريحة 3",
                "default": "",
                "group": "Slide 3",
                "groupAr": "شريحة 3",
            },
            {
                "key": "slide_3_cta_text",
                "type": "text",
                "label": "Slide 3 button",
                "labelAr": "زر الشريحة 3",
                "default": "",
                "group": "Slide 3",
                "groupAr": "شريحة 3",
            },
            {
                "key": "slide_3_cta_link",
                "type": "url",
                "label": "Slide 3 link",
                "labelAr": "رابط الشريحة 3",
                "default": "",
                "group": "Slide 3",
                "groupAr": "شريحة 3",
            },
        ],
        "presets": [
            {
                "name": "Slideshow",
                "nameAr": "عرض شرائح",
                "category": "Hero",
                "categoryAr": "رئيسي",
                "settings": {"autoplay": True, "interval": 5, "height": "medium"},
            }
        ],
    },
    # ── Multicolumn ────────────────────────────────────────────────
    {
        "type": "multicolumn",
        "name": "Multicolumn",
        "nameAr": "أعمدة متعددة",
        "limit": 0,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "لماذا تتسوق معنا؟",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "columns",
                "type": "range",
                "label": "Columns",
                "labelAr": "عدد الأعمدة",
                "default": 3,
                "min": 2,
                "max": 4,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "col_1_icon",
                "type": "text",
                "label": "Col 1 icon",
                "labelAr": "أيقونة 1",
                "default": "🚚",
                "group": "Column 1",
                "groupAr": "عمود 1",
            },
            {
                "key": "col_1_title",
                "type": "text",
                "label": "Col 1 title",
                "labelAr": "عنوان 1",
                "default": "شحن سريع",
                "group": "Column 1",
                "groupAr": "عمود 1",
            },
            {
                "key": "col_1_text",
                "type": "textarea",
                "label": "Col 1 text",
                "labelAr": "نص 1",
                "default": "توصيل لكل مصر خلال 2-5 أيام عمل",
                "group": "Column 1",
                "groupAr": "عمود 1",
            },
            {
                "key": "col_2_icon",
                "type": "text",
                "label": "Col 2 icon",
                "labelAr": "أيقونة 2",
                "default": "💎",
                "group": "Column 2",
                "groupAr": "عمود 2",
            },
            {
                "key": "col_2_title",
                "type": "text",
                "label": "Col 2 title",
                "labelAr": "عنوان 2",
                "default": "جودة مضمونة",
                "group": "Column 2",
                "groupAr": "عمود 2",
            },
            {
                "key": "col_2_text",
                "type": "textarea",
                "label": "Col 2 text",
                "labelAr": "نص 2",
                "default": "منتجات أصلية 100% مع ضمان الاستبدال",
                "group": "Column 2",
                "groupAr": "عمود 2",
            },
            {
                "key": "col_3_icon",
                "type": "text",
                "label": "Col 3 icon",
                "labelAr": "أيقونة 3",
                "default": "🔒",
                "group": "Column 3",
                "groupAr": "عمود 3",
            },
            {
                "key": "col_3_title",
                "type": "text",
                "label": "Col 3 title",
                "labelAr": "عنوان 3",
                "default": "دفع آمن",
                "group": "Column 3",
                "groupAr": "عمود 3",
            },
            {
                "key": "col_3_text",
                "type": "textarea",
                "label": "Col 3 text",
                "labelAr": "نص 3",
                "default": "بيانات الدفع مشفرة ومحمية بالكامل",
                "group": "Column 3",
                "groupAr": "عمود 3",
            },
            {
                "key": "col_4_icon",
                "type": "text",
                "label": "Col 4 icon",
                "labelAr": "أيقونة 4",
                "default": "📞",
                "group": "Column 4",
                "groupAr": "عمود 4",
            },
            {
                "key": "col_4_title",
                "type": "text",
                "label": "Col 4 title",
                "labelAr": "عنوان 4",
                "default": "دعم العملاء",
                "group": "Column 4",
                "groupAr": "عمود 4",
            },
            {
                "key": "col_4_text",
                "type": "textarea",
                "label": "Col 4 text",
                "labelAr": "نص 4",
                "default": "فريق خدمة العملاء متاح على مدار الساعة",
                "group": "Column 4",
                "groupAr": "عمود 4",
            },
        ],
        "presets": [
            {
                "name": "Features",
                "nameAr": "المميزات",
                "category": "Content",
                "categoryAr": "المحتوى",
                "settings": {"title": "لماذا تتسوق معنا؟", "columns": 3},
            }
        ],
    },
    # ── FAQ ────────────────────────────────────────────────────────
    {
        "type": "faq",
        "name": "FAQ",
        "nameAr": "الأسئلة الشائعة",
        "limit": 1,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "الأسئلة الشائعة",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "text",
                "label": "Subtitle",
                "labelAr": "وصف",
                "default": "إجابات على أكثر الأسئلة شيوعًا",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "q1",
                "type": "text",
                "label": "Question 1",
                "labelAr": "سؤال 1",
                "default": "ما هي مدة التوصيل؟",
                "group": "Q&A 1",
                "groupAr": "سؤال 1",
            },
            {
                "key": "a1",
                "type": "textarea",
                "label": "Answer 1",
                "labelAr": "إجابة 1",
                "default": "التوصيل يستغرق من 2 إلى 5 أيام عمل حسب المحافظة.",
                "group": "Q&A 1",
                "groupAr": "سؤال 1",
            },
            {
                "key": "q2",
                "type": "text",
                "label": "Question 2",
                "labelAr": "سؤال 2",
                "default": "ما هي سياسة الاستبدال والاسترجاع؟",
                "group": "Q&A 2",
                "groupAr": "سؤال 2",
            },
            {
                "key": "a2",
                "type": "textarea",
                "label": "Answer 2",
                "labelAr": "إجابة 2",
                "default": "يمكنك استبدال أو استرجاع المنتج خلال 14 يوم.",
                "group": "Q&A 2",
                "groupAr": "سؤال 2",
            },
            {
                "key": "q3",
                "type": "text",
                "label": "Question 3",
                "labelAr": "سؤال 3",
                "default": "ما هي طرق الدفع المتاحة؟",
                "group": "Q&A 3",
                "groupAr": "سؤال 3",
            },
            {
                "key": "a3",
                "type": "textarea",
                "label": "Answer 3",
                "labelAr": "إجابة 3",
                "default": "نقبل الدفع عند الاستلام والبطاقات البنكية والمحافظ الإلكترونية.",
                "group": "Q&A 3",
                "groupAr": "سؤال 3",
            },
            {
                "key": "q4",
                "type": "text",
                "label": "Question 4",
                "labelAr": "سؤال 4",
                "default": "هل المنتجات أصلية؟",
                "group": "Q&A 4",
                "groupAr": "سؤال 4",
            },
            {
                "key": "a4",
                "type": "textarea",
                "label": "Answer 4",
                "labelAr": "إجابة 4",
                "default": "جميع منتجاتنا أصلية 100% ومضمونة.",
                "group": "Q&A 4",
                "groupAr": "سؤال 4",
            },
            {
                "key": "q5",
                "type": "text",
                "label": "Question 5",
                "labelAr": "سؤال 5",
                "default": "",
                "group": "Q&A 5",
                "groupAr": "سؤال 5",
            },
            {
                "key": "a5",
                "type": "textarea",
                "label": "Answer 5",
                "labelAr": "إجابة 5",
                "default": "",
                "group": "Q&A 5",
                "groupAr": "سؤال 5",
            },
        ],
        "presets": [
            {
                "name": "FAQ",
                "nameAr": "الأسئلة الشائعة",
                "category": "Content",
                "categoryAr": "المحتوى",
                "settings": {},
            }
        ],
    },
    # ── Video ─────────────────────────────────────────────────────
    {
        "type": "video",
        "name": "Video",
        "nameAr": "فيديو",
        "limit": 0,
        "settings": [
            {
                "key": "video_url",
                "type": "url",
                "label": "Video URL (YouTube or Vimeo)",
                "labelAr": "رابط الفيديو",
                "default": "",
                "placeholder": "https://www.youtube.com/watch?v=...",
                "group": "Video",
                "groupAr": "الفيديو",
            },
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "subtitle",
                "type": "text",
                "label": "Subtitle",
                "labelAr": "وصف",
                "default": "",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "aspect_ratio",
                "type": "select",
                "label": "Aspect ratio",
                "labelAr": "نسبة العرض",
                "default": "16/9",
                "options": [
                    {"label": "16:9", "labelAr": "عريض", "value": "16/9"},
                    {"label": "4:3", "labelAr": "عادي", "value": "4/3"},
                    {"label": "1:1", "labelAr": "مربع", "value": "1/1"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "max_width",
                "type": "select",
                "label": "Max width",
                "labelAr": "العرض الأقصى",
                "default": "4xl",
                "options": [
                    {"label": "Medium", "labelAr": "متوسط", "value": "2xl"},
                    {"label": "Large", "labelAr": "كبير", "value": "4xl"},
                    {"label": "Full", "labelAr": "كامل", "value": "full"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [
            {
                "name": "Video",
                "nameAr": "فيديو",
                "category": "Media",
                "categoryAr": "الوسائط",
                "settings": {"aspect_ratio": "16/9", "max_width": "4xl"},
            }
        ],
    },
    # ── Logo Bar ──────────────────────────────────────────────────
    {
        "type": "logo-bar",
        "name": "Logo Bar",
        "nameAr": "شريط الشعارات",
        "limit": 1,
        "settings": [
            {
                "key": "title",
                "type": "text",
                "label": "Title",
                "labelAr": "العنوان",
                "default": "شركاؤنا",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "style",
                "type": "select",
                "label": "Style",
                "labelAr": "النمط",
                "default": "scroll",
                "options": [
                    {"label": "Scrolling", "labelAr": "متحرك", "value": "scroll"},
                    {"label": "Static grid", "labelAr": "شبكة ثابتة", "value": "grid"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "logo_1",
                "type": "image",
                "label": "Logo 1",
                "labelAr": "شعار 1",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
            {
                "key": "logo_2",
                "type": "image",
                "label": "Logo 2",
                "labelAr": "شعار 2",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
            {
                "key": "logo_3",
                "type": "image",
                "label": "Logo 3",
                "labelAr": "شعار 3",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
            {
                "key": "logo_4",
                "type": "image",
                "label": "Logo 4",
                "labelAr": "شعار 4",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
            {
                "key": "logo_5",
                "type": "image",
                "label": "Logo 5",
                "labelAr": "شعار 5",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
            {
                "key": "logo_6",
                "type": "image",
                "label": "Logo 6",
                "labelAr": "شعار 6",
                "default": "",
                "group": "Logos",
                "groupAr": "الشعارات",
            },
        ],
        "presets": [
            {
                "name": "Logo Bar",
                "nameAr": "شريط الشعارات",
                "category": "Brand",
                "categoryAr": "العلامة التجارية",
                "settings": {"title": "شركاؤنا", "style": "scroll"},
            }
        ],
    },
    # ── Page-level sections (not draggable on home page) ─────────────────────
    {
        "type": "products-page",
        "name": "Products Page",
        "nameAr": "صفحة المنتجات",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_view_toggle",
                "type": "checkbox",
                "label": "Show Grid/List Toggle",
                "labelAr": "إظهار زر تغيير العرض",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_category_subtitle",
                "type": "checkbox",
                "label": "Show Category Subtitle",
                "labelAr": "إظهار وصف الفئة",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "columns_desktop",
                "type": "range",
                "label": "Desktop Columns",
                "labelAr": "أعمدة الديسكتوب",
                "default": 4,
                "min": 2,
                "max": 5,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "columns_mobile",
                "type": "range",
                "label": "Mobile Columns",
                "labelAr": "أعمدة الموبايل",
                "default": 2,
                "min": 1,
                "max": 3,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [],
    },
    {
        "type": "product-detail",
        "name": "Product Detail Page",
        "nameAr": "صفحة تفاصيل المنتج",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_rating",
                "type": "checkbox",
                "label": "Show Rating",
                "labelAr": "إظهار التقييم",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_stock",
                "type": "checkbox",
                "label": "Show Stock Status",
                "labelAr": "إظهار حالة المخزون",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_whatsapp",
                "type": "checkbox",
                "label": "Show WhatsApp Button",
                "labelAr": "إظهار زر الواتساب",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_guarantees",
                "type": "checkbox",
                "label": "Show Trust Guarantees",
                "labelAr": "إظهار ضمانات الثقة",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_share_buttons",
                "type": "checkbox",
                "label": "Show Share Buttons",
                "labelAr": "إظهار أزرار المشاركة",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "related_products_count",
                "type": "range",
                "label": "Related Products Count",
                "labelAr": "عدد المنتجات المشابهة",
                "default": 4,
                "min": 0,
                "max": 8,
                "step": 1,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [],
    },
    {
        "type": "checkout",
        "name": "Checkout Page",
        "nameAr": "صفحة الدفع",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_steps",
                "type": "checkbox",
                "label": "Show Progress Steps",
                "labelAr": "إظهار خطوات التقدم",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_security_badge",
                "type": "checkbox",
                "label": "Show Security Badge",
                "labelAr": "إظهار شارة الأمان",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_free_shipping_hint",
                "type": "checkbox",
                "label": "Show Free Shipping Hint",
                "labelAr": "إظهار تنبيه الشحن المجاني",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_landmark",
                "type": "checkbox",
                "label": "Show Landmark Field",
                "labelAr": "إظهار حقل العلامة المميزة",
                "default": False,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_page_title",
                "type": "checkbox",
                "label": "Show Page Title",
                "labelAr": "إظهار عنوان الصفحة",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [],
    },
    {
        "type": "contact",
        "name": "Contact Page",
        "nameAr": "صفحة التواصل",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_working_hours",
                "type": "checkbox",
                "label": "Show Working Hours",
                "labelAr": "إظهار ساعات العمل",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [],
    },
    {
        "type": "order-confirmation",
        "name": "Order Confirmation",
        "nameAr": "تأكيد الطلب",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_progress",
                "type": "checkbox",
                "label": "Show Progress Steps",
                "labelAr": "إظهار خطوات التقدم",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_whatsapp",
                "type": "checkbox",
                "label": "Show WhatsApp Card",
                "labelAr": "إظهار بطاقة الواتساب",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_track_order",
                "type": "checkbox",
                "label": "Show Track Order Button",
                "labelAr": "إظهار زر تتبع الطلب",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_emoji",
                "type": "checkbox",
                "label": "Show Emoji in Title",
                "labelAr": "إظهار إيموجي في العنوان",
                "default": True,
                "group": "Content",
                "groupAr": "المحتوى",
            },
        ],
        "presets": [],
    },
    {
        "type": "profile",
        "name": "Profile Page",
        "nameAr": "صفحة الحساب",
        "limit": 1,
        "page_section": True,
        "settings": [
            {
                "key": "show_stats",
                "type": "checkbox",
                "label": "Show Account Stats",
                "labelAr": "إظهار إحصائيات الحساب",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_order_tracking",
                "type": "checkbox",
                "label": "Show Order Tracking",
                "labelAr": "إظهار تتبع الطلبات",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
        ],
        "presets": [],
    },
]

# ── Per-theme global settings schemas ────────────────────────────────────────

# These define the theme-wide settings (colors, fonts, layout) that appear
# at the top of the customization editor.  Each theme has its own defaults
# and may include theme-specific settings (e.g., neo-brutalism border width).

_FONT_OPTIONS = [
    {"label": "Cairo", "value": "Cairo"},
    {"label": "Tajawal", "value": "Tajawal"},
    {"label": "IBM Plex Sans Arabic", "value": "IBM Plex Sans Arabic"},
    {"label": "Noto Sans Arabic", "value": "Noto Sans Arabic"},
    {"label": "El Messiri", "value": "El Messiri"},
    {"label": "Almarai", "value": "Almarai"},
    {"label": "Changa", "value": "Changa"},
    {"label": "Rubik", "value": "Rubik"},
    {"label": "Readex Pro", "value": "Readex Pro"},
    {"label": "Inter", "value": "Inter"},
    {"label": "Poppins", "value": "Poppins"},
    {"label": "Space Grotesk", "value": "Space Grotesk"},
]


def _build_global_settings(
    *,
    primary: str,
    secondary: str,
    accent: str,
    background: str,
    text: str,
    radius: int = 12,
    radius_max: int = 24,
    extra: list[dict[str, Any]] | None = None,
    include_heading_font: bool = True,
) -> list[dict[str, Any]]:
    """Build a global settings list with theme-specific defaults."""
    settings: list[dict[str, Any]] = [
        {
            "key": "primary_color",
            "type": "color",
            "label": "Primary Color",
            "labelAr": "اللون الأساسي",
            "default": primary,
            "group": "Colors",
            "groupAr": "الألوان",
        },
        {
            "key": "secondary_color",
            "type": "color",
            "label": "Secondary Color",
            "labelAr": "اللون الثانوي",
            "default": secondary,
            "group": "Colors",
            "groupAr": "الألوان",
        },
        {
            "key": "accent_color",
            "type": "color",
            "label": "Accent Color",
            "labelAr": "لون مميز",
            "default": accent,
            "group": "Colors",
            "groupAr": "الألوان",
        },
        {
            "key": "background_color",
            "type": "color",
            "label": "Background",
            "labelAr": "الخلفية",
            "default": background,
            "group": "Colors",
            "groupAr": "الألوان",
        },
        {
            "key": "text_color",
            "type": "color",
            "label": "Text Color",
            "labelAr": "لون النص",
            "default": text,
            "group": "Colors",
            "groupAr": "الألوان",
        },
        {
            "key": "border_radius",
            "type": "range",
            "label": "Border Radius",
            "labelAr": "انحناء الحواف",
            "default": radius,
            "min": 0,
            "max": radius_max,
            "step": 2,
            "unit": "px",
            "group": "Layout",
            "groupAr": "التخطيط",
        },
        {
            "key": "enable_animations",
            "type": "checkbox",
            "label": "Enable Animations",
            "labelAr": "تفعيل الحركات",
            "default": True,
            "group": "Effects",
            "groupAr": "التأثيرات",
        },
    ]
    if extra:
        settings.extend(extra)
    if include_heading_font:
        settings.extend([
            {
                "key": "heading_font",
                "type": "font",
                "label": "Heading Font",
                "labelAr": "خط العناوين",
                "default": "Cairo",
                "options": _FONT_OPTIONS,
                "group": "Typography",
                "groupAr": "الخطوط",
            },
            {
                "key": "body_font",
                "type": "font",
                "label": "Body Font",
                "labelAr": "خط النصوص",
                "default": "Cairo",
                "options": _FONT_OPTIONS,
                "group": "Typography",
                "groupAr": "الخطوط",
            },
        ])
    return settings


THEME_GLOBAL_SETTINGS: dict[str, list[dict[str, Any]]] = {
    "modern": _build_global_settings(
        primary="#2C9277",
        secondary="#EDE8D0",
        accent="#C2EDE2",
        background="#FAF9F5",
        text="#1A1F2E",
        radius=12,
    ),
    "boutique": _build_global_settings(
        primary="#E0358F",
        secondary="#F0D6E4",
        accent="#F5D0E4",
        background="#FDF5F8",
        text="#1F0D14",
        radius=16,
    ),
    "elegant": _build_global_settings(
        primary="#734D26",
        secondary="#ECE4D5",
        accent="#E8D9C4",
        background="#F9F5EE",
        text="#231E16",
        radius=8,
    ),
    "skeuomorphic": _build_global_settings(
        primary="#2A7AC4",
        secondary="#DDD5C8",
        accent="#C8DAF0",
        background="#EAE2D6",
        text="#231E14",
        radius=12,
        extra=[
            {
                "key": "enable_depth",
                "type": "checkbox",
                "label": "Enable 3D Depth Effects",
                "labelAr": "تفعيل تأثيرات العمق",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enable_texture",
                "type": "checkbox",
                "label": "Enable Surface Texture",
                "labelAr": "تفعيل ملمس السطح",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
        ],
    ),
    "tech-wave": _build_global_settings(
        primary="#00D4FF",
        secondary="#1a2340",
        accent="#7B61FF",
        background="#0a0e1a",
        text="#e0e6ed",
        radius=12,
        extra=[
            {
                "key": "enable_neon_glow",
                "type": "checkbox",
                "label": "Enable Neon Glow",
                "labelAr": "تفعيل الإضاءة النيون",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enable_wave_animation",
                "type": "checkbox",
                "label": "Enable Wave Animation",
                "labelAr": "تفعيل حركة الأمواج",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enable_glassmorphism",
                "type": "checkbox",
                "label": "Enable Glassmorphism",
                "labelAr": "تفعيل الزجاجية",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "neon_color",
                "type": "color",
                "label": "Neon Glow Color",
                "labelAr": "لون الإضاءة النيون",
                "default": "#00D4FF",
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
        ],
    ),
    "neo-brutalism": _build_global_settings(
        primary="#a3e635",
        secondary="#fbbf24",
        accent="#f472b6",
        background="#fefce8",
        text="#1a1a1a",
        radius=8,
        radius_max=20,
        extra=[
            {
                "key": "border_width",
                "type": "select",
                "label": "Border Width",
                "labelAr": "سمك الحدود",
                "default": "3px",
                "options": [
                    {"label": "Thin (2px)", "labelAr": "رفيع (2px)", "value": "2px"},
                    {"label": "Medium (3px)", "labelAr": "متوسط (3px)", "value": "3px"},
                    {"label": "Thick (4px)", "labelAr": "سميك (4px)", "value": "4px"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "shadow_offset",
                "type": "select",
                "label": "Shadow Offset",
                "labelAr": "إزاحة الظل",
                "default": "4px",
                "options": [
                    {"label": "Small (3px)", "labelAr": "صغير (3px)", "value": "3px"},
                    {"label": "Medium (4px)", "labelAr": "متوسط (4px)", "value": "4px"},
                    {"label": "Large (6px)", "labelAr": "كبير (6px)", "value": "6px"},
                ],
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
        ],
    ),
    "editorial": _build_global_settings(
        primary="#2D6A4F",
        secondary="#40916C",
        accent="#95D5B2",
        background="#F0F2EC",
        text="#1B1B1B",
        radius=4,
        radius_max=16,
    ),
    "luxury-minimal": _build_global_settings(
        primary="#1A1A1A",
        secondary="#F5F5F5",
        accent="#B8860B",
        background="#FFFFFF",
        text="#1A1A1A",
        radius=0,
        radius_max=16,
    ),
    "rabbitsocks": _build_global_settings(
        primary="#000613",
        secondary="#635e54",
        accent="#001f3f",
        background="#f9f9f7",
        text="#000613",
        radius=0,
        radius_max=8,
        extra=[
            {
                "key": "enableAnimations",
                "type": "checkbox",
                "label": "Enable Animations",
                "labelAr": "تفعيل الحركات",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enableMarquee",
                "type": "checkbox",
                "label": "Enable Marquee Banner",
                "labelAr": "تفعيل الشريط المتحرك",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
        ],
    ),
    "bazar": _build_global_settings(
        primary="#FFB300",
        secondary="#FFF5E1",
        accent="#E6A200",
        background="#FFF5E1",
        text="#0a0a14",
        radius=16,
        radius_max=32,
        extra=[
            {
                "key": "color_cream",
                "type": "color",
                "label": "Cream Background",
                "labelAr": "خلفية كريمي",
                "default": "#FFF5E1",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "color_dark",
                "type": "color",
                "label": "Dark Background",
                "labelAr": "خلفية داكنة",
                "default": "#0a0a14",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "color_navy",
                "type": "color",
                "label": "Navy",
                "labelAr": "كحلي",
                "default": "#001f3f",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "enableMarquee",
                "type": "checkbox",
                "label": "Enable Scrolling Text",
                "labelAr": "تفعيل النص المتحرك",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enableWaves",
                "type": "checkbox",
                "label": "Enable Wave Dividers",
                "labelAr": "تفعيل فواصل الموجة",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
        ],
        include_heading_font=False,
    ),
    "gilded-glamour-boutique": _build_global_settings(
        primary="#B1A670",
        secondary="#F7F3EC",
        accent="#8A7F53",
        background="#F7F3EC",
        text="#000000",
        radius=0,
        radius_max=16,
        extra=[
            {
                "key": "color_gold_light",
                "type": "color",
                "label": "Gold Light",
                "labelAr": "ذهبي فاتح",
                "default": "#C8BF93",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "color_olive",
                "type": "color",
                "label": "Olive Accent",
                "labelAr": "زيتوني",
                "default": "#636A47",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "color_soft_pink",
                "type": "color",
                "label": "Soft Pink",
                "labelAr": "وردي ناعم",
                "default": "#E2B4B4",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "color_sale",
                "type": "color",
                "label": "Sale Badge",
                "labelAr": "شارة التخفيض",
                "default": "#A20000",
                "group": "Colors",
                "groupAr": "الألوان",
            },
            {
                "key": "enable_parallax",
                "type": "checkbox",
                "label": "Enable Hero Parallax",
                "labelAr": "تفعيل تأثير المنظور للبانر",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enable_scroll_fill",
                "type": "checkbox",
                "label": "Enable Scroll-Fill Text",
                "labelAr": "تفعيل تأثير ملء النص بالتمرير",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "enable_hover_scale",
                "type": "checkbox",
                "label": "Enable Product Hover Scale",
                "labelAr": "تفعيل تكبير المنتج عند المرور",
                "default": True,
                "group": "Effects",
                "groupAr": "التأثيرات",
            },
            {
                "key": "product_grid_columns",
                "type": "select",
                "label": "Product Grid Columns",
                "labelAr": "أعمدة شبكة المنتجات",
                "default": "5",
                "options": [
                    {"label": "3 Columns", "labelAr": "٣ أعمدة", "value": "3"},
                    {"label": "4 Columns", "labelAr": "٤ أعمدة", "value": "4"},
                    {"label": "5 Columns", "labelAr": "٥ أعمدة", "value": "5"},
                ],
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            {
                "key": "show_product_rating",
                "type": "checkbox",
                "label": "Show Product Rating",
                "labelAr": "إظهار تقييم المنتج",
                "default": True,
                "group": "Layout",
                "groupAr": "التخطيط",
            },
            # ── Hero ──
            {
                "key": "hero_headline",
                "type": "text",
                "label": "Hero Headline",
                "labelAr": "عنوان البانر الرئيسي",
                "default": "Timeless Elegance",
                "group": "Hero",
                "groupAr": "البانر الرئيسي",
            },
            {
                "key": "hero_subtitle",
                "type": "text",
                "label": "Hero Subtitle",
                "labelAr": "العنوان الفرعي للبانر",
                "default": "Curated Collections for the Modern Connoisseur",
                "group": "Hero",
                "groupAr": "البانر الرئيسي",
            },
            {
                "key": "hero_cta_text",
                "type": "text",
                "label": "Hero CTA Button Text",
                "labelAr": "نص زر البانر",
                "default": "Explore Collection",
                "group": "Hero",
                "groupAr": "البانر الرئيسي",
            },
            {
                "key": "hero_image_url",
                "type": "text",
                "label": "Hero Background Image URL",
                "labelAr": "رابط صورة خلفية البانر",
                "default": "",
                "group": "Hero",
                "groupAr": "البانر الرئيسي",
            },
            # ── Content ──
            {
                "key": "featured_badge_text",
                "type": "text",
                "label": "Featured Product Badge Text",
                "labelAr": "نص شارة المنتج المميز",
                "default": "Limited Edition",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "grid_title",
                "type": "text",
                "label": "Product Grid Section Title",
                "labelAr": "عنوان قسم المنتجات",
                "default": "Our Collection",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "grid_subtitle",
                "type": "text",
                "label": "Product Grid Section Subtitle",
                "labelAr": "العنوان الفرعي لقسم المنتجات",
                "default": "Discover our carefully curated selection",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "brand_statement",
                "type": "text",
                "label": "Brand Statement Headline",
                "labelAr": "عنوان بيان العلامة التجارية",
                "default": "Where Heritage Meets Modern Luxury",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "brand_statement_body",
                "type": "textarea",
                "label": "Brand Statement Body",
                "labelAr": "نص بيان العلامة التجارية",
                "default": "Every piece in our collection tells a story of exceptional craftsmanship.",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            {
                "key": "new_badge_text",
                "type": "text",
                "label": "New Arrival Badge Text",
                "labelAr": "نص شارة المنتج الجديد",
                "default": "New Arrival",
                "group": "Content",
                "groupAr": "المحتوى",
            },
            # ── Footer ──
            {
                "key": "footer_tagline",
                "type": "text",
                "label": "Footer Tagline",
                "labelAr": "الشعار في التذييل",
                "default": "Curating timeless pieces for the modern connoisseur.",
                "group": "Footer",
                "groupAr": "التذييل",
            },
            {
                "key": "newsletter_title",
                "type": "text",
                "label": "Newsletter Title",
                "labelAr": "عنوان النشرة البريدية",
                "default": "Join the Inner Circle",
                "group": "Footer",
                "groupAr": "التذييل",
            },
            {
                "key": "newsletter_subtitle",
                "type": "text",
                "label": "Newsletter Subtitle",
                "labelAr": "العنوان الفرعي للنشرة البريدية",
                "default": "Exclusive previews & early access",
                "group": "Footer",
                "groupAr": "التذييل",
            },
            {
                "key": "newsletter_button_text",
                "type": "text",
                "label": "Newsletter Button Text",
                "labelAr": "نص زر النشرة البريدية",
                "default": "Subscribe",
                "group": "Footer",
                "groupAr": "التذييل",
            },
        ],
    ),
}

# ── Per-theme default home templates ─────────────────────────────────────────

THEME_DEFAULT_TEMPLATES: dict[str, dict[str, Any]] = {
    "modern": {
        "name": "home",
        "sections": {
            "hero_main": {"id": "hero_main", "type": "hero", "settings": {}},
            "categories_main": {
                "id": "categories_main",
                "type": "categories",
                "settings": {},
            },
            "new_arrivals_fc": {
                "id": "new_arrivals_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "وصل حديثاً ✨",
                    "subtitle": "أحدث المنتجات اللي ضفناها",
                    "collection_tag": "new",
                    "view_all_link": "/products?tag=new",
                },
            },
            "promo_main": {"id": "promo_main", "type": "promo-banner", "settings": {}},
            "best_sellers_fc": {
                "id": "best_sellers_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "الأكثر مبيعاً 🔥",
                    "subtitle": "المنتجات اللي الناس بتحبها",
                    "collection_tag": "bestseller",
                    "view_all_link": "/products?tag=bestseller",
                },
            },
            "testimonials_main": {
                "id": "testimonials_main",
                "type": "testimonials",
                "settings": {},
            },
            "newsletter_main": {
                "id": "newsletter_main",
                "type": "newsletter",
                "settings": {},
            },
        },
        "order": [
            "hero_main",
            "categories_main",
            "new_arrivals_fc",
            "promo_main",
            "best_sellers_fc",
            "testimonials_main",
            "newsletter_main",
        ],
    },
    "neo-brutalism": {
        "name": "home",
        "sections": {
            "hero_main": {"id": "hero_main", "type": "hero", "settings": {}},
            "marquee_main": {"id": "marquee_main", "type": "marquee", "settings": {}},
            "categories_main": {
                "id": "categories_main",
                "type": "categories",
                "settings": {},
            },
            "new_arrivals_fc": {
                "id": "new_arrivals_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "وصل حديثاً ✨",
                    "subtitle": "أحدث المنتجات اللي ضفناها",
                    "collection_tag": "new",
                    "view_all_link": "/products?tag=new",
                },
            },
            "promo_main": {"id": "promo_main", "type": "promo-banner", "settings": {}},
            "best_sellers_fc": {
                "id": "best_sellers_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "الأكثر مبيعاً 🔥",
                    "subtitle": "المنتجات اللي الناس بتحبها",
                    "collection_tag": "bestseller",
                    "view_all_link": "/products?tag=bestseller",
                },
            },
            "testimonials_main": {
                "id": "testimonials_main",
                "type": "testimonials",
                "settings": {},
            },
            "newsletter_main": {
                "id": "newsletter_main",
                "type": "newsletter",
                "settings": {},
            },
        },
        "order": [
            "hero_main",
            "marquee_main",
            "categories_main",
            "new_arrivals_fc",
            "promo_main",
            "best_sellers_fc",
            "testimonials_main",
            "newsletter_main",
        ],
    },
    "editorial": {
        "name": "home",
        "sections": {
            "hero_main": {"id": "hero_main", "type": "hero", "settings": {}},
            "categories_main": {
                "id": "categories_main",
                "type": "categories",
                "settings": {},
            },
            "new_arrivals_fc": {
                "id": "new_arrivals_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "وصل حديثاً",
                    "subtitle": "",
                    "collection_tag": "new",
                    "view_all_link": "/products?tag=new",
                },
            },
            "best_sellers_fc": {
                "id": "best_sellers_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "الأكثر مبيعاً",
                    "subtitle": "",
                    "collection_tag": "bestseller",
                    "view_all_link": "/products?tag=bestseller",
                },
            },
            "newsletter_main": {
                "id": "newsletter_main",
                "type": "newsletter",
                "settings": {},
            },
        },
        "order": [
            "hero_main",
            "categories_main",
            "new_arrivals_fc",
            "best_sellers_fc",
            "newsletter_main",
        ],
    },
    "luxury-minimal": {
        "name": "home",
        "sections": {
            "hero_main": {"id": "hero_main", "type": "hero", "settings": {}},
            "categories_main": {
                "id": "categories_main",
                "type": "categories",
                "settings": {},
            },
            "new_arrivals_fc": {
                "id": "new_arrivals_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "وصل حديثاً",
                    "subtitle": "",
                    "collection_tag": "new",
                    "view_all_link": "/products?tag=new",
                },
            },
            "best_sellers_fc": {
                "id": "best_sellers_fc",
                "type": "featured-collection",
                "settings": {
                    "title": "الأكثر مبيعاً",
                    "subtitle": "",
                    "collection_tag": "bestseller",
                    "view_all_link": "/products?tag=bestseller",
                },
            },
            "newsletter_main": {
                "id": "newsletter_main",
                "type": "newsletter",
                "settings": {},
            },
        },
        "order": [
            "hero_main",
            "categories_main",
            "new_arrivals_fc",
            "best_sellers_fc",
            "newsletter_main",
        ],
    },
}

# Themes that share the same template as modern
for _theme_id in ("boutique", "elegant", "skeuomorphic", "tech-wave"):
    THEME_DEFAULT_TEMPLATES[_theme_id] = THEME_DEFAULT_TEMPLATES["modern"]

THEME_DEFAULT_TEMPLATES["rabbitsocks"] = {
    "name": "home",
    "sections": {
        "hero_main": {
            "id": "hero_main",
            "type": "hero",
            "settings": {
                "headline": "اكتشف أناقة الجوارب الفاخرة",
                "subtitle": "رفاهية هادئة في كل تفصيلة",
                "cta_text": "تسوق الآن",
                "cta_link": "/products",
            },
        },
        "marquee_main": {
            "id": "marquee_main",
            "type": "marquee",
            "settings": {"text": "رفاهية هادئة", "repeat": 8},
        },
        "featured_fc": {
            "id": "featured_fc",
            "type": "featured-collection",
            "settings": {
                "title": "التشكيلة المميزة",
                "collection_tag": "trending",
                "view_all_link": "/products",
            },
        },
        "categories_main": {
            "id": "categories_main",
            "type": "categories",
            "settings": {
                "title": "تسوق حسب الفئة",
                "columns_desktop": 4,
                "columns_mobile": 2,
            },
        },
        "newsletter_main": {
            "id": "newsletter_main",
            "type": "newsletter",
            "settings": {
                "title": "انضم إلينا",
                "subtitle": "اشترك في نشرتنا البريدية لتصلك أحدث التشكيلات والعروض الحصرية",
            },
        },
    },
    "order": [
        "hero_main",
        "marquee_main",
        "featured_fc",
        "categories_main",
        "newsletter_main",
    ],
}

THEME_DEFAULT_TEMPLATES["bazar"] = {
    "name": "home",
    "sections": {
        "hero_main": {
            "id": "hero_main",
            "type": "hero",
            "settings": {
                "headline": "BAZAR DREAMS",
                "subtitle": "COME TO LIFE",
                "cta_text": "SCROLL TO DISCOVER",
                "cta_link": "/products",
            },
        },
        "categories_main": {
            "id": "categories_main",
            "type": "categories",
            "settings": {},
        },
        "featured_fc": {
            "id": "featured_fc",
            "type": "featured-collection",
            "settings": {
                "title": "THE COLLECTION",
                "subtitle": "SEASONAL EDIT",
                "collection_tag": "new",
                "product_count": 8,
                "columns": 4,
                "view_all_text": "VIEW ALL",
            },
        },
        "newsletter_main": {
            "id": "newsletter_main",
            "type": "newsletter",
            "settings": {
                "title": "JOIN THE CIRCLE",
                "subtitle": "Early access to limited drops and exclusive content.",
                "button_text": "JOIN",
            },
        },
    },
    "order": [
        "hero_main",
        "categories_main",
        "featured_fc",
        "newsletter_main",
    ],
}

THEME_DEFAULT_TEMPLATES["gilded-glamour-boutique"] = {
    "name": "home",
    "sections": {
        "hero_main": {
            "id": "hero_main",
            "type": "hero",
            "settings": {
                "headline": "THE NEW EMPIRE",
                "subtitle": "Curated Excellence & Timeless Precision",
                "cta_text": "Discover Collection",
                "cta_link": "/products",
            },
        },
        "categories_main": {
            "id": "categories_main",
            "type": "categories",
            "settings": {"title": "Curated Verticals", "max_items": 3},
        },
        "featured_fc": {
            "id": "featured_fc",
            "type": "featured-collection",
            "settings": {
                "title": "Crafted for the Eternal Wardrobe",
                "subtitle": "The Artisan Way",
                "collection_tag": "new",
                "product_count": 5,
                "columns": 5,
                "view_all_text": "View All",
            },
        },
        "promo_main": {
            "id": "promo_main",
            "type": "promo-banner",
            "settings": {
                "headline": "WHERE HERITAGE MEETS THE FUTURE",
                "subtitle": "Every thread tells a story, every silhouette commands a room, and every piece is destined to become an heirloom.",
            },
        },
        "bestsellers_fc": {
            "id": "bestsellers_fc",
            "type": "featured-collection",
            "settings": {
                "title": "Empire Essentials",
                "subtitle": "Most Loved",
                "collection_tag": "bestseller",
                "product_count": 5,
                "columns": 5,
                "view_all_text": "Shop All",
            },
        },
        "newsletter_main": {
            "id": "newsletter_main",
            "type": "newsletter",
            "settings": {
                "title": "Newsletter",
                "subtitle": "Join the empire. Be first to know.",
                "button_text": "Join",
                "placeholder": "Your email",
            },
        },
    },
    "order": [
        "hero_main",
        "categories_main",
        "featured_fc",
        "promo_main",
        "bestsellers_fc",
        "newsletter_main",
    ],
}

# ── Default page templates (shared across all themes) ────────────────────────

_PAGE_TEMPLATES: dict[str, dict[str, Any]] = {
    "products": {
        "name": "products",
        "sections": {
            "products_page_main": {
                "id": "products_page_main",
                "type": "products-page",
                "settings": {},
            }
        },
        "order": ["products_page_main"],
    },
    "product-detail": {
        "name": "product-detail",
        "sections": {
            "pdp_main": {"id": "pdp_main", "type": "product-detail", "settings": {}}
        },
        "order": ["pdp_main"],
    },
    "checkout": {
        "name": "checkout",
        "sections": {
            "checkout_main": {"id": "checkout_main", "type": "checkout", "settings": {}}
        },
        "order": ["checkout_main"],
    },
    "contact": {
        "name": "contact",
        "sections": {
            "contact_main": {"id": "contact_main", "type": "contact", "settings": {}}
        },
        "order": ["contact_main"],
    },
    "order-confirmation": {
        "name": "order-confirmation",
        "sections": {
            "oc_main": {"id": "oc_main", "type": "order-confirmation", "settings": {}}
        },
        "order": ["oc_main"],
    },
    "profile": {
        "name": "profile",
        "sections": {
            "profile_main": {"id": "profile_main", "type": "profile", "settings": {}}
        },
        "order": ["profile_main"],
    },
}

# ── Lookup helpers ───────────────────────────────────────────────────────────

_SECTION_SCHEMA_MAP: dict[str, dict[str, Any]] = {s["type"]: s for s in SECTION_SCHEMAS}


def get_section_schemas() -> list[dict[str, Any]]:
    """Return all available section schemas."""
    return SECTION_SCHEMAS


def get_theme_schema(theme_id: str) -> dict[str, Any] | None:
    """Return the full schema bundle for a given theme."""
    global_settings = THEME_GLOBAL_SETTINGS.get(theme_id)
    if global_settings is None:
        return None

    home_template = THEME_DEFAULT_TEMPLATES.get(theme_id)
    default_templates: dict[str, Any] = {**_PAGE_TEMPLATES}
    if home_template:
        default_templates["home"] = home_template

    return {
        "theme_id": theme_id,
        "global_settings": global_settings,
        "sections": SECTION_SCHEMAS,
        "default_templates": default_templates,
    }
