// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "gilded-categories": {
    "title"?: string;
    "max_items"?: number;
  };
  "gilded-featured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "product_ids"?: string;
    "collection_tag"?: "new" | "bestseller" | "featured" | "sale";
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "gilded-footer": {
    "brand_name"?: string;
    "logo_url"?: string;
    "footer_text"?: string;
    "show_newsletter"?: boolean;
    "newsletter_title"?: string;
    "newsletter_subtitle"?: string;
  };
  "gilded-header": {
    "brand_name"?: string;
    "logo_url"?: string;
    "show_announcement"?: boolean;
    "announcement_text"?: string;
    "show_search"?: boolean;
    "show_cart"?: boolean;
  };
  "gilded-hero": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "hero_image_url"?: string;
    "hero_image_mobile"?: string;
    "enable_parallax"?: boolean;
  };
  "gilded-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "gilded-not-found": {
    "status_label"?: string;
    "headline"?: string;
    "subhead"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "gilded-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "gilded-products-page": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "gilded-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "gilded-promo-banner": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "gilded-rich-text": {
    "title"?: string;
    "content"?: string;
  };
  "gilded-search-results": {
    "empty_heading"?: string;
    "search_placeholder"?: string;
    "no_results_text"?: string;
    "columns_desktop"?: number;
  };
  "gilded-testimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
