// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "nb-about": {
    "eyebrow"?: string;
    "headline"?: string;
    "quote"?: string;
    "description"?: string;
    "image"?: string;
    "value_1_title"?: string;
    "value_1_text"?: string;
    "value_2_title"?: string;
    "value_2_text"?: string;
    "value_3_title"?: string;
    "value_3_text"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "contact_cta_text"?: string;
    "contact_cta_link"?: string;
  };
  "nb-announcement-bar": {
    "text"?: string;
    "link_url"?: string;
    "link_text"?: string;
    "dismissible"?: boolean;
  };
  "nb-contact": {
    "eyebrow"?: string;
    "title"?: string;
    "subtitle"?: string;
    "name_label"?: string;
    "phone_label"?: string;
    "message_label"?: string;
    "submit_text"?: string;
    "success_title"?: string;
    "success_message"?: string;
    "show_working_hours"?: boolean;
    "hours_weekdays_label"?: string;
    "hours_weekdays_value"?: string;
    "hours_friday_label"?: string;
    "hours_friday_value"?: string;
    "show_map"?: boolean;
    "map_embed_url"?: string;
  };
  "nb-order-confirmation-section": {
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "show_emoji"?: boolean;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
  };
  "nb-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "nb-products-page": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "nb-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "nbcategories": {
    "title"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
  };
  "nbfeatured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "product_ids"?: string;
    "collection_tag"?: "new" | "bestseller" | "featured" | "sale";
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "nbhero": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "secondary_text"?: string;
    "secondary_link"?: string;
    "hero_image_url"?: string;
    "hero_image_2"?: string;
    "hero_image_3"?: string;
    "hero_image_4"?: string;
    "show_trust_strip"?: boolean;
  };
  "nbmarquee": {
    "text"?: string;
    "repeat_count"?: number;
  };
  "nbnewsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "nbpromo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "diagonal_text"?: string;
    "image_url"?: string;
  };
  "nbtestimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
