// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "bz-about-section": {
    "hdr_hero"?: unknown;
    "eyebrow"?: string;
    "headline"?: string;
    "quote"?: string;
    "image_url"?: string;
    "hdr_who"?: unknown;
    "who_label"?: string;
    "who_headline"?: string;
    "description"?: string;
    "hdr_marquee"?: unknown;
    "marquee_text"?: string;
    "hdr_values"?: unknown;
    "values_label"?: string;
    "values_headline"?: string;
    "hdr_cta"?: unknown;
    "cta_label"?: string;
    "cta_headline"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "contact_cta_text"?: string;
    "contact_cta_link"?: string;
  };
  "bz-cart": {
    "empty_headline"?: string;
    "empty_subhead"?: string;
    "empty_cta_label"?: string;
    "empty_cta_href"?: string;
    "populated_title"?: string;
    "checkout_cta_label"?: string;
    "continue_label"?: string;
    "subtotal_label"?: string;
    "shipping_label"?: string;
    "total_label"?: string;
    "free_label"?: string;
    "shipping_calc_label"?: string;
    "free_shipping_threshold"?: number;
  };
  "bz-contact": {
    "hdr_hero"?: unknown;
    "eyebrow"?: string;
    "headline"?: string;
    "intro"?: string;
    "hdr_channels"?: unknown;
    "channels_label"?: string;
    "channels_headline"?: string;
    "hdr_form"?: unknown;
    "form_label"?: string;
    "form_headline"?: string;
    "name_label"?: string;
    "email_label"?: string;
    "phone_label"?: string;
    "message_label"?: string;
    "submit_text"?: string;
    "hdr_success"?: unknown;
    "success_title"?: string;
    "success_message"?: string;
    "hdr_hours"?: unknown;
    "show_hours"?: boolean;
    "hours_label"?: string;
    "hours_headline"?: string;
    "hours_description"?: string;
    "hours_weekdays_label"?: string;
    "hours_weekdays_value"?: string;
    "hours_friday_label"?: string;
    "hours_friday_value"?: string;
    "hours_note"?: string;
  };
  "bz-featured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "view_all_label"?: string;
    "view_all_link"?: string;
    "product_ids"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "bz-footer": {
    "brand_name"?: string;
    "footer_text"?: string;
    "newsletter_title"?: string;
    "newsletter_copy"?: string;
    "newsletter_button_label"?: string;
    "newsletter_button_success"?: string;
  };
  "bz-header": {
    "brand_name"?: string;
    "logo_url"?: string;
    "announcement_enabled"?: boolean;
    "announcement_text"?: string;
    "announcement_text_ar"?: string;
    "announcement_mode"?: "slide" | "static";
    "announcement_speed"?: number;
    "show_search"?: boolean;
    "show_cart"?: boolean;
  };
  "bz-hero": {
    "letter"?: string;
    "letter_ar"?: string;
    "headline"?: string;
    "subline"?: string;
    "tagline"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "secondary_cta_text"?: string;
    "secondary_cta_link"?: string;
    "trust_text"?: string;
    "hero_image_url"?: string;
    "color_scheme"?: "auto" | "light" | "dark";
    "blob_decoration"?: boolean;
    "show_wave_divider"?: boolean;
  };
  "bz-image-with-text": {
    "label"?: string;
    "headline"?: string;
    "quote"?: string;
    "body"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
    "color_scheme"?: "dark" | "light";
  };
  "bz-marquee": {
    "text"?: string;
    "repeat_count"?: number;
  };
  "bz-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "bz-not-found": {
    "status_label"?: string;
    "headline"?: string;
    "subhead"?: string;
    "cta_label"?: string;
    "cta_href"?: string;
  };
  "bz-order-confirmation": {
    "hdr_content"?: unknown;
    "eyebrow"?: string;
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "hdr_labels"?: unknown;
    "order_number_label"?: string;
    "total_label"?: string;
    "delivery_label"?: string;
    "delivery_value"?: string;
    "status_label"?: string;
    "status_value"?: string;
    "hdr_display"?: unknown;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
    "track_order_text"?: string;
  };
  "bz-product-detail": {
    "add_to_cart_label"?: string;
    "added_label"?: string;
    "out_of_stock_label"?: string;
    "in_stock_label"?: string;
    "quantity_label"?: string;
    "home_label"?: string;
    "shop_label"?: string;
  };
  "bz-product-grid": {
    "title"?: string;
    "subtitle"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
    "show_filters"?: boolean;
    "page_size"?: number;
    "empty_state_text"?: string;
  };
  "bz-profile": {
    "hdr_content"?: unknown;
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "hdr_layout"?: unknown;
    "show_stats"?: boolean;
  };
  "bz-promo-banner": {
    "image_url"?: string;
    "subtitle"?: string;
    "card_label"?: string;
    "title"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "bz-related-products": {
    "title"?: string;
    "count"?: number;
  };
  "bz-rich-text": {
    "content"?: string;
  };
  "bz-search-results": {
    "placeholder_when_no_query"?: string;
    "search_placeholder"?: string;
    "no_results_text"?: string;
    "columns_desktop"?: number;
  };
  "bz-testimonials": {
    "title"?: string;
  };
}
