// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "by-cart": {
    "empty_headline"?: string;
    "empty_subhead"?: string;
    "empty_cta_label"?: string;
    "empty_cta_href"?: string;
    "populated_title"?: string;
    "checkout_cta_label"?: string;
  };
  "by-footer": {
    "brand_name"?: string;
    "tagline"?: string;
    "address"?: string;
    "phone"?: string;
    "footer_menu_handle"?: string;
    "show_newsletter"?: boolean;
    "newsletter_title"?: string;
    "newsletter_copy"?: string;
    "newsletter_button_label"?: string;
    "newsletter_button_success"?: string;
    "copyright_text"?: string;
    "credit_text"?: string;
    "credit_link_label"?: string;
  };
  "by-header": {
    "brand_name"?: string;
    "brand_tagline"?: string;
    "brand_monogram"?: string;
    "show_search"?: boolean;
    "show_cart"?: boolean;
    "nav_menu_handle"?: string;
  };
  "by-hero": {
    "eyebrow"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "by-menu": {
    "eyebrow"?: string;
    "title"?: string;
    "subtitle"?: string;
    "view_all_label"?: string;
    "view_all_link"?: string;
    "card_cta_label"?: string;
    "empty_category_text"?: string;
  };
  "by-not-found": {
    "status_label"?: string;
    "headline"?: string;
    "subhead"?: string;
    "cta_label"?: string;
    "cta_href"?: string;
  };
  "by-order-confirmation": {
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "show_emoji"?: boolean;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
  };
  "by-product-detail": {
    "recommended_title"?: string;
    "addons_title"?: string;
    "badge_1_text"?: string;
    "badge_2_text"?: string;
    "quantity_label"?: string;
    "add_to_cart_label"?: string;
    "save_label"?: string;
    "addons_total_label"?: string;
    "reco_cta_label"?: string;
  };
  "by-product-grid": {
    "title"?: string;
    "subtitle"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
    "empty_state_text"?: string;
  };
  "by-profile-section": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "by-related-products": {
    "title"?: string;
    "count"?: number;
  };
  "by-rich-text": {
    "heading"?: string;
    "body"?: string;
  };
  "by-scroll-story": {
    "eyebrow"?: string;
    "title"?: string;
  };
  "by-search-results": {
    "placeholder_when_no_query"?: string;
    "no_results_text"?: string;
    "columns_desktop"?: number;
  };
}
