"""initial_schema_with_tenant_id

Revision ID: f06433870b55
Revises:
Create Date: 2026-01-19 05:27:53.194425

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f06433870b55"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "CUSTOMER",
                "STORE_OWNER",
                "STORE_ADMIN",
                "STORE_STAFF",
                "SUPER_ADMIN",
                name="userrole",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "PENDING_VERIFICATION",
                name="userstatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_email"), "users", ["email"], unique=True, schema="public"
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subdomain", sa.String(length=63), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_tenants_owner_id"),
        "tenants",
        ["owner_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_tenants_subdomain"),
        "tenants",
        ["subdomain"],
        unique=True,
        schema="public",
    )
    op.create_table(
        "stores",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("banner_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                "PENDING_APPROVAL",
                name="storestatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "default_currency",
            sa.Enum(
                "USD",
                "EUR",
                "GBP",
                "SAR",
                "AED",
                "KWD",
                "BHD",
                "QAR",
                "OMR",
                "EGP",
                name="currency",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stores_owner_id"),
        "stores",
        ["owner_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_stores_slug"), "stores", ["slug"], unique=True, schema="public"
    )
    op.create_index(
        op.f("ix_public_stores_tenant_id"),
        "stores",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "categories",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["public.categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["store_id"], ["public.stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_categories_parent_id"),
        "categories",
        ["parent_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_categories_slug"),
        "categories",
        ["slug"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_categories_store_id"),
        "categories",
        ["store_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_categories_tenant_id"),
        "categories",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "customers",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("accepts_marketing", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("default_address_id", sa.UUID(), nullable=True),
        sa.Column("total_orders", sa.Integer(), nullable=False),
        sa.Column("total_spent", sa.Integer(), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["public.stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_customers_email"),
        "customers",
        ["email"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_customers_store_id"),
        "customers",
        ["store_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_customers_tenant_id"),
        "customers",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_customers_user_id"),
        "customers",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "orders",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "AUTHORIZED",
                "PAID",
                "PARTIALLY_REFUNDED",
                "REFUNDED",
                "FAILED",
                name="paymentstatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "fulfillment_status",
            sa.Enum(
                "UNFULFILLED",
                "PARTIALLY_FULFILLED",
                "FULFILLED",
                name="fulfillmentstatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column(
            "line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "billing_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("subtotal", sa.Integer(), nullable=False),
        sa.Column("shipping_cost", sa.Integer(), nullable=False),
        sa.Column("tax_amount", sa.Integer(), nullable=False),
        sa.Column("discount_amount", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("payment_id", sa.String(length=255), nullable=True),
        sa.Column("shipping_method", sa.String(length=100), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["public.customers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["store_id"], ["public.stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_customer_id"),
        "orders",
        ["customer_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_order_number"),
        "orders",
        ["order_number"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_payment_id"),
        "orders",
        ["payment_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_status"),
        "orders",
        ["status"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_store_id"),
        "orders",
        ["store_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_orders_tenant_id"),
        "orders",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "products",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column(
            "product_type",
            sa.Enum(
                "PHYSICAL", "DIGITAL", "SERVICE", name="producttype", schema="public"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "ARCHIVED",
                "OUT_OF_STOCK",
                name="productstatus",
                schema="public",
            ),
            nullable=False,
        ),
        sa.Column("price_amount", sa.Integer(), nullable=False),
        sa.Column("price_currency", sa.String(length=3), nullable=False),
        sa.Column("compare_at_price", sa.Integer(), nullable=True),
        sa.Column("cost_price", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["public.categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["store_id"], ["public.stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["public.tenants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_category_id"),
        "products",
        ["category_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_sku"),
        "products",
        ["sku"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_slug"),
        "products",
        ["slug"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_status"),
        "products",
        ["status"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_store_id"),
        "products",
        ["store_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_products_tenant_id"),
        "products",
        ["tenant_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_products_tenant_id"), table_name="products", schema="public"
    )
    op.drop_index(
        op.f("ix_public_products_store_id"), table_name="products", schema="public"
    )
    op.drop_index(
        op.f("ix_public_products_status"), table_name="products", schema="public"
    )
    op.drop_index(
        op.f("ix_public_products_slug"), table_name="products", schema="public"
    )
    op.drop_index(
        op.f("ix_public_products_sku"), table_name="products", schema="public"
    )
    op.drop_index(
        op.f("ix_public_products_category_id"), table_name="products", schema="public"
    )
    op.drop_table("products", schema="public")
    op.drop_index(
        op.f("ix_public_orders_tenant_id"), table_name="orders", schema="public"
    )
    op.drop_index(
        op.f("ix_public_orders_store_id"), table_name="orders", schema="public"
    )
    op.drop_index(op.f("ix_public_orders_status"), table_name="orders", schema="public")
    op.drop_index(
        op.f("ix_public_orders_payment_id"), table_name="orders", schema="public"
    )
    op.drop_index(
        op.f("ix_public_orders_order_number"), table_name="orders", schema="public"
    )
    op.drop_index(
        op.f("ix_public_orders_customer_id"), table_name="orders", schema="public"
    )
    op.drop_table("orders", schema="public")
    op.drop_index(
        op.f("ix_public_customers_user_id"), table_name="customers", schema="public"
    )
    op.drop_index(
        op.f("ix_public_customers_tenant_id"), table_name="customers", schema="public"
    )
    op.drop_index(
        op.f("ix_public_customers_store_id"), table_name="customers", schema="public"
    )
    op.drop_index(
        op.f("ix_public_customers_email"), table_name="customers", schema="public"
    )
    op.drop_table("customers", schema="public")
    op.drop_index(
        op.f("ix_public_categories_tenant_id"), table_name="categories", schema="public"
    )
    op.drop_index(
        op.f("ix_public_categories_store_id"), table_name="categories", schema="public"
    )
    op.drop_index(
        op.f("ix_public_categories_slug"), table_name="categories", schema="public"
    )
    op.drop_index(
        op.f("ix_public_categories_parent_id"), table_name="categories", schema="public"
    )
    op.drop_table("categories", schema="public")
    op.drop_index(
        op.f("ix_public_stores_tenant_id"), table_name="stores", schema="public"
    )
    op.drop_index(op.f("ix_public_stores_slug"), table_name="stores", schema="public")
    op.drop_index(
        op.f("ix_public_stores_owner_id"), table_name="stores", schema="public"
    )
    op.drop_table("stores", schema="public")
    op.drop_index(
        op.f("ix_public_tenants_subdomain"), table_name="tenants", schema="public"
    )
    op.drop_index(
        op.f("ix_public_tenants_owner_id"), table_name="tenants", schema="public"
    )
    op.drop_table("tenants", schema="public")
    op.drop_index(op.f("ix_public_users_email"), table_name="users", schema="public")
    op.drop_table("users", schema="public")
    # ### end Alembic commands ###
