"""add customer auth and addresses

Revision ID: 2d2b2176a338
Revises: c0e6c0c21b45
Create Date: 2026-01-23 23:59:45.673848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d2b2176a338'
down_revision: Union[str, None] = 'f06433870b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('label', sa.Enum('HOME', 'WORK', 'OTHER', name='addresslabel', schema='public'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['public.customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_customer_addresses_tenant_id'), 'customer_addresses', ['tenant_id'], unique=False, schema='public')
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('categories_tenant_id_fkey'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('categories_store_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('customers_tenant_id_fkey'), 'customers', type_='foreignkey')
    op.drop_constraint(op.f('customers_store_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', schema='public'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               type_=sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED', name='paymentstatus', schema='public'),
               existing_nullable=False)
    op.alter_column('orders', 'fulfillment_status',
               existing_type=postgresql.ENUM('UNFULFILLED', 'PARTIALLY_FULFILLED', 'FULFILLED', name='fulfillmentstatus'),
               type_=sa.Enum('UNFULFILLED', 'PARTIALLY_FULFILLED', 'FULFILLED', name='fulfillmentstatus', schema='public'),
               existing_nullable=False)
    op.drop_constraint(op.f('orders_tenant_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_store_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('products', 'product_type',
               existing_type=postgresql.ENUM('PHYSICAL', 'DIGITAL', 'SERVICE', name='producttype'),
               type_=sa.Enum('PHYSICAL', 'DIGITAL', 'SERVICE', name='producttype', schema='public'),
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', 'OUT_OF_STOCK', name='productstatus'),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'OUT_OF_STOCK', name='productstatus', schema='public'),
               existing_nullable=False)
    op.drop_constraint(op.f('products_tenant_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_store_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('stores', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', name='storestatus'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', name='storestatus', schema='public'),
               existing_nullable=False)
    op.alter_column('stores', 'default_currency',
               existing_type=postgresql.ENUM('USD', 'EUR', 'GBP', 'SAR', 'AED', 'KWD', 'BHD', 'QAR', 'OMR', 'EGP', name='currency'),
               type_=sa.Enum('USD', 'EUR', 'GBP', 'SAR', 'AED', 'KWD', 'BHD', 'QAR', 'OMR', 'EGP', name='currency', schema='public'),
               existing_nullable=False)
    op.drop_constraint(op.f('stores_tenant_id_fkey'), 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('tenants_owner_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CUSTOMER', 'STORE_OWNER', 'STORE_ADMIN', 'STORE_STAFF', 'SUPER_ADMIN', name='userrole'),
               type_=sa.Enum('CUSTOMER', 'STORE_OWNER', 'STORE_ADMIN', 'STORE_STAFF', 'SUPER_ADMIN', name='userrole', schema='public'),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus', schema='public'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus', schema='public'),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CUSTOMER', 'STORE_OWNER', 'STORE_ADMIN', 'STORE_STAFF', 'SUPER_ADMIN', name='userrole', schema='public'),
               type_=postgresql.ENUM('CUSTOMER', 'STORE_OWNER', 'STORE_ADMIN', 'STORE_STAFF', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'tenants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_owner_id_fkey'), 'tenants', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'stores', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('stores_tenant_id_fkey'), 'stores', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stores', 'default_currency',
               existing_type=sa.Enum('USD', 'EUR', 'GBP', 'SAR', 'AED', 'KWD', 'BHD', 'QAR', 'OMR', 'EGP', name='currency', schema='public'),
               type_=postgresql.ENUM('USD', 'EUR', 'GBP', 'SAR', 'AED', 'KWD', 'BHD', 'QAR', 'OMR', 'EGP', name='currency'),
               existing_nullable=False)
    op.alter_column('stores', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', name='storestatus', schema='public'),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', name='storestatus'),
               existing_nullable=False)
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('products_store_id_fkey'), 'products', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('products_tenant_id_fkey'), 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'OUT_OF_STOCK', name='productstatus', schema='public'),
               type_=postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', 'OUT_OF_STOCK', name='productstatus'),
               existing_nullable=False)
    op.alter_column('products', 'product_type',
               existing_type=sa.Enum('PHYSICAL', 'DIGITAL', 'SERVICE', name='producttype', schema='public'),
               type_=postgresql.ENUM('PHYSICAL', 'DIGITAL', 'SERVICE', name='producttype'),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_store_id_fkey'), 'orders', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_tenant_id_fkey'), 'orders', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'fulfillment_status',
               existing_type=sa.Enum('UNFULFILLED', 'PARTIALLY_FULFILLED', 'FULFILLED', name='fulfillmentstatus', schema='public'),
               type_=postgresql.ENUM('UNFULFILLED', 'PARTIALLY_FULFILLED', 'FULFILLED', name='fulfillmentstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED', name='paymentstatus', schema='public'),
               type_=postgresql.ENUM('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', schema='public'),
               type_=postgresql.ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'customers', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('customers_store_id_fkey'), 'customers', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('customers_tenant_id_fkey'), 'customers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'categories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('categories_store_id_fkey'), 'categories', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('categories_tenant_id_fkey'), 'categories', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_public_customer_addresses_tenant_id'), table_name='customer_addresses', schema='public')
    op.drop_index(op.f('ix_public_customer_addresses_customer_id'), table_name='customer_addresses', schema='public')
    op.drop_table('customer_addresses', schema='public')
    # ### end Alembic commands ###
