"""Shared brand base for all NUMU transactional emails.

Single source of truth for:
- Brand palette
- Typography (Cairo for Arabic body, Aref Ruqaa for the نُمو wordmark)
- Email-safe logo block
- Header / footer / wrapper helpers
- Egyptian Arabic copy bank used across templates

Egyptian Arabic ("ar") is the primary/default language. English ("en") is
provided as a secondary fallback.
"""

from __future__ import annotations

# ──────────────────────────────────────────────────────────────────────────
# Brand palette
# ──────────────────────────────────────────────────────────────────────────
NAVY = "#0A1A3D"  # deep navy from logo background
NAVY_BRIGHT = "#1034A6"  # interactive / accent navy
HERO_BG = "#0d1117"  # landing-page hero base (hsl(222 30% 7%))
GOLD = "#D4AF37"  # signature gold
GOLD_DARK = "#B8941F"  # gold hover/pressed
CREAM = "#FAF7F0"  # warm off-white background
INK = "#1A1A2E"  # body text
MUTED = "#6C757D"  # secondary text
HAIRLINE = "#E9ECEF"  # dividers
SUCCESS = "#1F8A4C"
DANGER = "#C2362F"

FONT_AR = "'Alexandria', 'Segoe UI', 'Tahoma', Arial, sans-serif"
FONT_LATIN = "'Alexandria', 'Inter', 'Segoe UI', Arial, sans-serif"
FONT_BRAND_AR = "'Aref Ruqaa', 'Traditional Arabic', serif"

# NUMU brand wordmark — نُمو set in Aref Ruqaa Bold, white on transparent.
# Generated by scripts/generate_wordmark.py via headless Chromium so the
# calligraphic shaping (cascading noon→meem→waw + dhamma) is correct.
# WORDMARK_WIDTH/HEIGHT come from the generator's sidecar file.
from src.infrastructure.external_services.resend.email_templates._assets.wordmark import (  # noqa: E402
    WORDMARK_HEIGHT,
    WORDMARK_WIDTH,
)


def _wordmark_url() -> str:
    """Return the absolute URL for the white wordmark PNG.

    Reads from settings.brand_assets_base_url so dev/staging/prod can
    each override the host. Defaults to the landing-page asset which
    is already served by the production nginx config.
    """
    try:
        from src.config import settings

        base = settings.brand_assets_base_url.rstrip("/")
    except Exception:
        base = "https://numueg.app"
    return f"{base}/numu-logo-white.png"


# ──────────────────────────────────────────────────────────────────────────
# Logo block (email-safe — uses inline base64 PNG so the Aref Ruqaa
# rendering is preserved across every email client, even when Google
# Fonts are blocked or stripped).
# ──────────────────────────────────────────────────────────────────────────
def _logo_block(language: str = "ar") -> str:
    """Render the official NUMU brand logo as a hosted PNG image.

    Uses an absolute URL (not a data URL) because Gmail strips base64
    data: URIs from <img src>. The image is the same Arabic wordmark
    shipped with the landing page, recolored white for the dark email
    header.
    """
    # Display height in px. The Aref Ruqaa wordmark is roughly 0.75 wide
    # vs tall (the dhamma sits above the noon, the waw descends below),
    # so we anchor on height and let the width fall out.
    display_h = 140
    display_w = max(1, round(WORDMARK_WIDTH * display_h / WORDMARK_HEIGHT))
    url = _wordmark_url()
    return f"""
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:0 auto;">
      <tr>
        <td align="center" style="text-align:center;">
          <img src="{url}"
               width="{display_w}" height="{display_h}"
               alt="NUMU"
               style="display:block;width:{display_w}px;height:{display_h}px;max-width:{display_w}px;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;">
        </td>
      </tr>
    </table>
    """


# ──────────────────────────────────────────────────────────────────────────
# CSS — generated dynamically so RTL/LTR share one source
# ──────────────────────────────────────────────────────────────────────────
def _styles(language: str) -> str:
    is_ar = language == "ar"
    direction = "rtl" if is_ar else "ltr"
    align = "right" if is_ar else "left"
    align_opp = "left" if is_ar else "right"
    font_family = FONT_AR if is_ar else FONT_LATIN
    line_height = "1.85" if is_ar else "1.65"
    # Alexandria is a single font that covers both Latin and Arabic glyphs,
    # so the same import works for both directions.
    font_import = "@import url('https://fonts.googleapis.com/css2?family=Alexandria:wght@300;400;500;600;700;800&family=Aref+Ruqaa:wght@400;700&display=swap');"

    # Step indicators get mirrored padding for RTL.
    step_dot_margin = (
        "margin-left:14px;margin-right:0;"
        if is_ar
        else "margin-right:14px;margin-left:0;"
    )
    step_line_margin = (
        "margin-right:15px;margin-left:0;"
        if is_ar
        else "margin-left:15px;margin-right:0;"
    )
    accent_border_side = "border-right" if is_ar else "border-left"

    return f"""
<style>
  {font_import}
  body {{ margin:0; padding:0; background:{CREAM}; color:{INK}; font-family:{font_family}; line-height:{line_height}; direction:{direction}; -webkit-font-smoothing:antialiased; }}
  table {{ border-collapse:collapse; }}
  img {{ border:0; outline:none; text-decoration:none; max-width:100%; }}
  a {{ color:{NAVY_BRIGHT}; text-decoration:none; }}
  .brand {{ font-family:{FONT_BRAND_AR}; font-weight:700; }}

  .page {{ width:100%; background:{CREAM}; padding:32px 16px; }}
  .wrapper {{ max-width:600px; margin:0 auto; background:#ffffff; border-radius:16px; overflow:hidden; box-shadow:0 4px 32px rgba(10,26,61,0.08); }}

  .header {{
    background-color:{HERO_BG};
    background-image:
      radial-gradient(circle at 12% 8%, rgba(59,130,246,0.55) 0%, rgba(59,130,246,0.18) 28%, transparent 58%),
      radial-gradient(circle at 88% 92%, rgba(168,85,247,0.32) 0%, rgba(168,85,247,0.10) 35%, transparent 65%),
      radial-gradient(rgba(255,255,255,0.06) 1px, transparent 1px);
    background-size: 100% 100%, 100% 100%, 26px 26px;
    background-position: 0 0, 0 0, 0 0;
    background-repeat: no-repeat, no-repeat, repeat;
    padding:48px 28px 40px; text-align:center; position:relative;
  }}
  .header::after {{ content:""; display:block; height:3px; background:linear-gradient(90deg,transparent 0%,{GOLD} 50%,transparent 100%); margin:32px -28px -40px; }}
  .header h1 {{ color:#ffffff; margin:22px 0 6px; font-size:24px; font-weight:700; letter-spacing:{"0" if is_ar else "-0.3px"}; font-family:{font_family}; }}
  .header p {{ color:rgba(255,255,255,0.78); margin:0; font-size:14px; font-family:{font_family}; }}
  .header .badge {{ display:inline-block; background:rgba(212,175,55,0.18); color:{GOLD}; border:1px solid rgba(212,175,55,0.4); font-size:12px; padding:5px 14px; border-radius:999px; margin-top:14px; font-weight:600; letter-spacing:0.5px; font-family:{FONT_LATIN}; direction:ltr; }}

  .body {{ padding:36px 32px 8px; text-align:{align}; }}
  .body p {{ margin:0 0 16px; font-size:15px; color:{INK}; }}
  .body h2 {{ font-size:18px; color:{NAVY}; margin:24px 0 12px; font-weight:700; }}
  .lead {{ font-size:16px; color:{INK}; }}
  .muted {{ color:{MUTED}; font-size:13px; }}

  .panel {{ background:{CREAM}; border:1px solid {HAIRLINE}; border-radius:12px; padding:22px; margin:22px 0; {accent_border_side}:4px solid {GOLD}; }}
  .panel .label {{ font-size:11px; color:{MUTED}; text-transform:uppercase; letter-spacing:1.2px; margin:0 0 6px; font-family:{FONT_LATIN}; }}
  .panel .value {{ font-size:22px; font-weight:700; color:{NAVY}; margin:0; }}

  .code-box {{ text-align:center; background:#fff; border:2px dashed {GOLD}; border-radius:12px; padding:22px 28px; margin:24px 0; }}
  .code-box .digits {{ font-family:'Inter','Segoe UI',monospace; font-size:36px; font-weight:700; letter-spacing:10px; color:{NAVY}; margin:0; direction:ltr; display:inline-block; }}
  .code-box .hint {{ color:{MUTED}; font-size:12px; margin:10px 0 0; }}

  table.items {{ width:100%; margin:18px 0; }}
  table.items th {{ text-align:{align}; padding:12px 14px; background:{CREAM}; color:{MUTED}; font-size:11px; text-transform:uppercase; letter-spacing:0.8px; border-bottom:2px solid {HAIRLINE}; font-family:{FONT_LATIN}; }}
  table.items th.price {{ text-align:{align_opp}; }}
  table.items td {{ padding:14px; border-bottom:1px solid {HAIRLINE}; font-size:14px; color:{INK}; }}
  table.items td.price {{ text-align:{align_opp}; font-weight:600; color:{NAVY}; direction:ltr; }}
  table.items tr.total td {{ background:{CREAM}; font-weight:700; font-size:16px; color:{NAVY}; padding:16px 14px; }}

  .btn {{ display:inline-block; padding:15px 38px; background:{GOLD}; color:#ffffff !important; text-decoration:none; border-radius:8px; font-weight:700; font-size:15px; box-shadow:0 4px 14px rgba(212,175,55,0.35); font-family:{font_family}; }}
  .btn:hover {{ background:{GOLD_DARK}; }}
  .btn-outline {{ display:inline-block; padding:13px 32px; background:transparent; color:{NAVY} !important; text-decoration:none; border:2px solid {NAVY}; border-radius:8px; font-weight:600; font-size:14px; font-family:{font_family}; }}
  .center {{ text-align:center; }}
  .divider {{ height:1px; background:{HAIRLINE}; margin:28px 0; border:0; }}

  .steps {{ margin:24px 0; }}
  .step {{ display:flex; align-items:flex-start; }}
  .step-dot {{ width:30px; min-width:30px; height:30px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:14px; font-weight:700; flex-shrink:0; {step_dot_margin} font-family:{FONT_LATIN}; }}
  .step-dot.done {{ background:{SUCCESS}; color:#fff; }}
  .step-dot.active {{ background:{GOLD}; color:#fff; box-shadow:0 0 0 4px rgba(212,175,55,0.18); }}
  .step-dot.pending {{ background:{HAIRLINE}; color:{MUTED}; }}
  .step-line {{ width:2px; height:22px; {step_line_margin} }}
  .step-line.done {{ background:{SUCCESS}; }}
  .step-line.pending {{ background:{HAIRLINE}; }}
  .step-text .title {{ font-weight:600; font-size:14px; color:{INK}; margin:4px 0 0; }}
  .step-text .sub {{ font-size:12px; color:{MUTED}; margin:2px 0 0; }}

  .footer {{ padding:28px 24px 32px; text-align:center; background:{CREAM}; border-top:1px solid {HAIRLINE}; }}
  .footer p {{ margin:0; font-size:12px; color:{MUTED}; line-height:1.7; }}
  .footer .links a {{ color:{NAVY_BRIGHT}; margin:0 8px; }}
  .footer .mark {{ display:inline-block; margin-bottom:10px; font-family:{FONT_BRAND_AR}; font-size:22px; color:{NAVY}; font-weight:700; }}

  @media only screen and (max-width:600px) {{
    .body {{ padding:28px 20px; }}
    .header {{ padding:30px 20px; }}
    .header h1 {{ font-size:21px; }}
  }}
</style>
"""


# ──────────────────────────────────────────────────────────────────────────
# Footer copy (Egyptian Arabic + English)
# ──────────────────────────────────────────────────────────────────────────
_FOOTER_COPY = {
    "ar": {
        "tagline": "منصة التجارة الإلكترونية للتجار المصريين",
        "help": "محتاج مساعدة؟ رد على الإيميل ده أو كلّمنا.",
        "rights": 'جميع الحقوق محفوظة &copy; 2026 <span class="brand">نُمو</span>.',
        "address": "نُمو • القاهرة، مصر",
    },
    "en": {
        "tagline": "E-commerce for Egyptian merchants",
        "help": "Need help? Reply to this email and we'll get back to you.",
        "rights": "&copy; 2026 NUMU. All rights reserved.",
        "address": "NUMU • Cairo, Egypt",
    },
}


def _footer(language: str) -> str:
    f = _FOOTER_COPY.get(language, _FOOTER_COPY["ar"])
    return f"""
<div class="footer">
  <div class="mark">نُمو</div>
  <p>{f["tagline"]}</p>
  <p style="margin-top:10px;">{f["help"]}</p>
  <p style="margin-top:14px;">{f["rights"]}</p>
  <p style="margin-top:6px;font-size:11px;">{f["address"]}</p>
</div>
"""


# ──────────────────────────────────────────────────────────────────────────
# Header builder — bg styles are inlined directly so Gmail / Outlook
# can't strip them, and the dark color is preserved by Gmail dark mode.
# ──────────────────────────────────────────────────────────────────────────
def header(
    title: str,
    subtitle: str | None = None,
    badge: str | None = None,
    language: str = "ar",
) -> str:
    """Build a branded header with the inline PNG wordmark and title."""
    font_family = FONT_AR if language == "ar" else FONT_LATIN

    badge_html = (
        f'<div style="margin-top:14px;">'
        f'<span style="display:inline-block;background:rgba(212,175,55,0.2);color:{GOLD};'
        f"border:1px solid rgba(212,175,55,0.45);font-size:12px;padding:5px 14px;"
        f"border-radius:999px;font-weight:600;letter-spacing:0.5px;"
        f'font-family:{FONT_LATIN};direction:ltr;">{badge}</span></div>'
        if badge
        else ""
    )

    sub_html = (
        f'<p style="color:#cdd2dc;margin:0;font-size:14px;font-family:{font_family};">{subtitle}</p>'
        if subtitle
        else ""
    )

    # Inline background — three layered radial gradients on top of the
    # solid hero color, plus the dot grid. The solid color is the
    # guaranteed Outlook fallback.
    header_bg_style = (
        f"background-color:{HERO_BG};"
        "background-image:"
        "radial-gradient(circle at 12% 8%, rgba(59,130,246,0.55) 0%, rgba(59,130,246,0.18) 28%, transparent 58%),"
        "radial-gradient(circle at 88% 92%, rgba(168,85,247,0.32) 0%, rgba(168,85,247,0.10) 35%, transparent 65%),"
        "radial-gradient(rgba(255,255,255,0.06) 1px, transparent 1px);"
        "background-size:100% 100%, 100% 100%, 26px 26px;"
        "background-position:0 0, 0 0, 0 0;"
        "background-repeat:no-repeat, no-repeat, repeat;"
    )

    # Gmail mobile auto-inverts elements with light text on a CSS-only
    # dark background. The only reliable way to keep a dark hero is the
    # legacy `<table bgcolor="...">` attribute — Gmail respects it and
    # leaves the background alone. We then layer the radial gradients on
    # top via inline `style` so capable clients (Apple Mail, iOS Mail,
    # Yahoo) still get the glows.
    return f"""
    <!--[if mso]>
    <v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="mso-width-percent:1000;height:300px;">
      <v:fill type="solid" color="{HERO_BG}"/>
      <v:textbox inset="0,0,0,0">
    <![endif]-->
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="{HERO_BG}" class="gmail-fix" style="background-color:{HERO_BG};">
      <tr>
        <td bgcolor="{HERO_BG}" align="center" valign="middle" class="gmail-fix" style="{header_bg_style}padding:48px 28px 40px;text-align:center;color:#ffffff;">
          {_logo_block(language)}
          <h1 style="color:#ffffff;margin:24px 0 8px;font-size:24px;font-weight:700;font-family:{font_family};line-height:1.4;mso-line-height-rule:exactly;">{title}</h1>
          {sub_html}
          {badge_html}
        </td>
      </tr>
      <tr>
        <td bgcolor="{HERO_BG}" height="3" style="background-color:{HERO_BG};line-height:3px;font-size:0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td height="3" style="height:3px;line-height:3px;font-size:0;background-color:{GOLD};">&nbsp;</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <!--[if mso]>
      </v:textbox>
    </v:rect>
    <![endif]-->
    """


# ──────────────────────────────────────────────────────────────────────────
# Wrapper — call this from every template
# ──────────────────────────────────────────────────────────────────────────
def wrap(inner_html: str, language: str = "ar", preheader: str | None = None) -> str:
    """Wrap rendered template body in a full HTML document with brand chrome.

    Args:
        inner_html: The template body (header + body sections).
        language: 'ar' (default, Egyptian Arabic, RTL) or 'en'.
        preheader: Optional inbox preview text.
    """
    is_ar = language == "ar"
    direction = "rtl" if is_ar else "ltr"
    preheader_html = (
        f'<div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:transparent;">{preheader}</div>'
        if preheader
        else ""
    )
    return f"""<!DOCTYPE html>
<html lang="{language}" dir="{direction}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="only light">
<meta name="supported-color-schemes" content="only light">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>NUMU</title>
{_styles(language)}
<style type="text/css">
  /* Force light color scheme — stops Gmail / Outlook.com mobile from
     auto-inverting our dark hero header into a light one. */
  :root {{ color-scheme: only light; supported-color-schemes: only light; }}
  /* Gmail-specific dark-mode override: force the header cell to keep
     its dark background and white text even when the user is in dark
     mode. The [data-ogsc] selector targets Outlook.com Gmail-style
     rendering. */
  u + .body .gmail-fix {{ background-color: {HERO_BG} !important; color: #ffffff !important; }}
  [data-ogsc] .gmail-fix {{ background-color: {HERO_BG} !important; color: #ffffff !important; }}
  @media (prefers-color-scheme: dark) {{
    .gmail-fix {{ background-color: {HERO_BG} !important; color: #ffffff !important; }}
  }}
</style>
<!--[if mso]>
<style type="text/css">
  body, table, td, div, p, a {{ font-family: Tahoma, Arial, sans-serif !important; }}
</style>
<![endif]-->
</head>
<body class="body" style="margin:0;padding:0;background:{CREAM};direction:{direction};width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
{preheader_html}
<!--[if mso]>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:{CREAM};"><tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="background:#ffffff;"><tr><td>
<![endif]-->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:{CREAM};">
  <tr>
    <td align="center" style="padding:32px 16px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" class="wrapper" style="max-width:600px;width:100%;margin:0 auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 32px rgba(10,26,61,0.08);">
        <tr>
          <td>
            {inner_html}
            {_footer(language)}
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<!--[if mso]>
</td></tr></table>
</td></tr></table>
<![endif]-->
</body>
</html>"""
