// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "kg-about": {
    "eyebrow"?: string;
    "headline"?: string;
    "quote"?: string;
    "description"?: string;
    "image"?: string;
    "value_1_title"?: string;
    "value_1_text"?: string;
    "value_2_title"?: string;
    "value_2_text"?: string;
    "value_3_title"?: string;
    "value_3_text"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "contact_cta_text"?: string;
    "contact_cta_link"?: string;
  };
  "kg-contact": {
    "eyebrow"?: string;
    "title"?: string;
    "subtitle"?: string;
    "name_label"?: string;
    "phone_label"?: string;
    "message_label"?: string;
    "submit_text"?: string;
    "success_title"?: string;
    "success_message"?: string;
    "show_working_hours"?: boolean;
    "hours_weekdays_label"?: string;
    "hours_weekdays_value"?: string;
    "hours_friday_label"?: string;
    "hours_friday_value"?: string;
    "show_map"?: boolean;
    "map_embed_url"?: string;
  };
  "kg-order-confirmation": {
    "title"?: string;
    "subtitle"?: string;
    "continue_shopping_text"?: string;
    "continue_shopping_link"?: string;
    "show_emoji"?: boolean;
    "show_progress"?: boolean;
    "show_whatsapp"?: boolean;
    "show_track_order"?: boolean;
  };
  "kg-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "kg-products-page": {
    "show_view_toggle"?: boolean;
    "show_category_subtitle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "kg-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "kgcategories": {
    "title"?: string;
  };
  "kgfeatured": {
    "title"?: string;
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
  };
  "kghero": {
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "hero_image_url"?: string;
  };
  "kgnewsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "kgpromo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
  };
  "kgtestimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
