// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "lux-cart": {
    "empty_headline"?: string;
    "empty_subhead"?: string;
    "empty_cta_label"?: string;
    "empty_cta_href"?: string;
    "populated_title"?: string;
    "checkout_cta_label"?: string;
    "subtotal_label"?: string;
    "shipping_label"?: string;
    "total_label"?: string;
    "free_label"?: string;
    "shipping_calc_label"?: string;
    "free_shipping_threshold"?: number;
  };
  "lux-categories": {
    "title"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
  };
  "lux-featured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_ids"?: string;
    "collection_tag"?: "new" | "bestseller";
    "product_count"?: number;
    "columns"?: number;
  };
  "lux-footer": {
    "brand_name"?: string;
    "logo_url"?: string;
    "footer_text"?: string;
  };
  "lux-header": {
    "brand_name"?: string;
    "logo_url"?: string;
    "header_layout"?: "logo-center" | "logo-left" | "stacked" | "logo-right";
    "show_announcement"?: boolean;
    "announcement_text"?: string;
    "announcement_color"?: string;
    "announcement_text_color"?: string;
    "show_search"?: boolean;
    "show_cart"?: boolean;
  };
  "lux-hero": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "hero_image_url"?: string;
  };
  "lux-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "placeholder"?: string;
    "button_text"?: string;
    "success_text"?: string;
  };
  "lux-not-found": {
    "heading"?: string;
    "eyebrow"?: string;
    "subtext"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
  };
  "lux-order-confirmation": {
    "prefix_text"?: string;
    "title_text"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "show_track_order"?: boolean;
    "show_progress"?: boolean;
    "show_guarantees"?: boolean;
  };
  "lux-product-detail": {
    "breadcrumb_home"?: string;
    "breadcrumb_shop"?: string;
    "add_to_cart_text"?: string;
    "sold_out_text"?: string;
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "shipping_label"?: string;
    "shipping_desc"?: string;
    "returns_label"?: string;
    "returns_desc"?: string;
    "authentic_label"?: string;
    "authentic_desc"?: string;
    "show_related_products"?: boolean;
    "related_title"?: string;
    "related_products_count"?: number;
  };
  "lux-product-grid": {
    "title"?: string;
    "show_category_subtitle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "products_per_page"?: number;
    "show_view_toggle"?: boolean;
  };
  "lux-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "password_title"?: string;
    "show_stats"?: boolean;
  };
  "lux-promo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "image_url"?: string;
  };
  "lux-rich-text": {
    "heading"?: string;
    "body"?: string;
  };
  "lux-search-results": {
    "title"?: string;
    "columns_desktop"?: number;
  };
  "lux-testimonials": {
    "title"?: string;
  };
}
