// This file is auto-generated by @numueg/theme-plugin. Do not edit.
// Regenerated on every `numu-theme build` from schemas/sections/*.json.
//
// Use it to get typed section settings:
//   import type { SectionSettings } from './__generated__/sections';
//   const s = settings as SectionSettings['hero'];

export interface SectionSettings {
  "modern-categories": {
    "title"?: string;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
    "max_items"?: number;
  };
  "modern-featured-collection": {
    "title"?: string;
    "subtitle"?: string;
    "product_ids"?: unknown;
    "collection_tag"?: "new" | "bestseller" | "featured" | "sale";
    "view_all_text"?: string;
    "view_all_link"?: string;
    "product_count"?: number;
    "columns"?: number;
  };
  "modern-hero": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "secondary_text"?: string;
    "secondary_link"?: string;
    "hero_image_url"?: string;
    "hero_image_mobile"?: string;
    "hero_image_2"?: string;
    "hero_image_3"?: string;
    "hero_image_4"?: string;
    "show_trust_strip"?: boolean;
  };
  "modern-newsletter": {
    "title"?: string;
    "subtitle"?: string;
    "button_text"?: string;
    "placeholder"?: string;
  };
  "modern-product-detail": {
    "show_rating"?: boolean;
    "show_stock"?: boolean;
    "show_guarantees"?: boolean;
    "show_related_products"?: boolean;
    "related_products_count"?: number;
  };
  "modern-products-page": {
    "show_view_toggle"?: boolean;
    "columns_desktop"?: number;
    "columns_mobile"?: number;
  };
  "modern-profile": {
    "title"?: string;
    "orders_title"?: string;
    "addresses_title"?: string;
    "settings_title"?: string;
    "show_stats"?: boolean;
  };
  "modern-promo-banner": {
    "badge_text"?: string;
    "headline"?: string;
    "subtitle"?: string;
    "cta_text"?: string;
    "cta_link"?: string;
    "diagonal_text"?: string;
    "image_url"?: string;
  };
  "modern-testimonials": {
    "title"?: string;
    "review_1_name"?: string;
    "review_1_city"?: string;
    "review_1_text"?: string;
    "review_1_rating"?: number;
    "review_2_name"?: string;
    "review_2_city"?: string;
    "review_2_text"?: string;
    "review_2_rating"?: number;
    "review_3_name"?: string;
    "review_3_city"?: string;
    "review_3_text"?: string;
    "review_3_rating"?: number;
  };
}
