"""Render the نُمو wordmark in Aref Ruqaa via headless Chromium.

PIL has no complex-text shaping engine, so it can't run the GSUB
substitutions Aref Ruqaa needs for proper letter joining + the dhamma.
Headless Chromium uses HarfBuzz internally and gives us pixel-perfect
calligraphic rendering — exactly what you'd see in the browser.

Output is written to `_assets/numu-logo-white.png` plus a sidecar
`wordmark.py` with width/height constants so the email base module can
embed an `<img width=… height=…>` without runtime browser dependency.

Run once whenever the wordmark changes.
"""

import base64
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
ASSETS = (
    ROOT
    / "src"
    / "infrastructure"
    / "external_services"
    / "resend"
    / "email_templates"
    / "_assets"
)
FONT_PATH = ASSETS / "ArefRuqaa-Bold.ttf"
OUT_PNG = ASSETS / "numu-logo-white.png"
OUT_PY = ASSETS / "wordmark.py"

# Render at high DPR then downsample for crisp output on retina screens.
DPR = 4
FONT_PX = 260
TEXT = "نُمو"
COLOR = "#ffffff"

font_b64 = base64.b64encode(FONT_PATH.read_bytes()).decode("ascii")
font_data_url = f"data:font/ttf;base64,{font_b64}"

# Generous padding (1× the font size on every side) so the dhamma above
# the noon and the descender of the waw never get clipped.
PAD_PX = FONT_PX

HTML = f"""<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<style>
  @font-face {{
    font-family: 'Aref Ruqaa Brand';
    src: url('{font_data_url}') format('truetype');
    font-weight: 700;
    font-display: block;
  }}
  html, body {{ margin: 0; padding: 0; background: transparent; }}
  body {{
    /* Inline-block + heavy padding gives Chromium / HarfBuzz plenty of
       room to draw the calligraphic ascenders and descenders without
       cropping. The auto-crop step below trims the empty space. */
    display: inline-block;
    padding: {PAD_PX}px;
    background: transparent;
  }}
  .wordmark {{
    font-family: 'Aref Ruqaa Brand', serif;
    font-weight: 700;
    font-size: {FONT_PX}px;
    line-height: 1;
    color: {COLOR};
    direction: rtl;
    white-space: nowrap;
    /* Let HarfBuzz apply Aref Ruqaa's default OpenType shaping —
       contextual joins, mark positioning, calligraphic ligatures. */
  }}
</style>
</head>
<body>
  <span class="wordmark" id="w">{TEXT}</span>
</body>
</html>
"""


def main() -> None:
    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context(
            viewport={"width": 1600, "height": 1200},
            device_scale_factor=DPR,
        )
        page = context.new_page()
        page.set_content(HTML, wait_until="networkidle")
        page.evaluate("document.fonts.ready")
        page.wait_for_timeout(300)

        # Full-page screenshot — captures the whole padded area so the
        # auto-crop step below can find the actual glyph bbox.
        png_bytes = page.screenshot(omit_background=True, full_page=True)
        browser.close()

    OUT_PNG.write_bytes(png_bytes)

    from PIL import Image

    img = Image.open(OUT_PNG).convert("RGBA")
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)

    # Add a small uniform padding so glyphs don't touch the edges
    pad = 12 * (DPR // 2)
    padded = Image.new(
        "RGBA", (img.width + pad * 2, img.height + pad * 2), (0, 0, 0, 0)
    )
    padded.paste(img, (pad, pad), img)

    # Downsample by 2 — keeps @2x density for retina at the displayed size
    final_w = padded.width // 2
    final_h = padded.height // 2
    final = padded.resize((final_w, final_h), Image.LANCZOS)
    final.save(OUT_PNG, "PNG", optimize=True)

    OUT_PY.write_text(
        '"""Auto-generated by scripts/generate_wordmark.py. Do not edit by hand."""\n'
        "\n"
        f"WORDMARK_WIDTH = {final_w}\n"
        f"WORDMARK_HEIGHT = {final_h}\n",
        encoding="ascii",
    )

    data = OUT_PNG.read_bytes()
    print(f"Wrote {OUT_PNG} ({len(data)} bytes, {final_w}x{final_h})")
    print(f"Wrote {OUT_PY}")


if __name__ == "__main__":
    main()
