"""Database models module."""

from src.infrastructure.database.models.audit import AuditLogModel
from src.infrastructure.database.models.base import (
    TenantMixin,
    TimestampMixin,
    UUIDMixin,
)

# Public schema models
from src.infrastructure.database.models.public import (
    CapiEventModel,
    CatalogMappingModel,
    ChannelConnectionModel,
    ChannelMessageModel,
    FeedbackModel,
    MessageThreadModel,
    StoreOnboardingModel,
    TenantModel,
    UserModel,
    WaitlistModel,
    WebhookEventModel,
)

# Tenant-scoped models (with tenant_id discriminator)
from src.infrastructure.database.models.tenant import (
    AutomationLogModel,
    AutomationRuleModel,
    CategoryModel,
    CouponModel,
    CustomerAddressModel,
    CustomerModel,
    InstapayIntentModel,
    InvoiceModel,
    MessageLogModel,
    NetworkContributionLogModel,
    NetworkReputationModel,
    OrderModel,
    PageViewModel,
    PaymentLinkSessionModel,
    PaymentProofModel,
    PaymentTransactionModel,
    ProductModel,
    RefundModel,
    RiskAssessmentModel,
    ShipmentModel,
    ShopifyAppSettingsModel,
    ShopifyInstallationModel,
    SocialConnectionModel,
    SocialPostModel,
    StoreModel,
    StoreThemeModel,
    ThemeAssetModel,
    ThemeModel,
    ThemeVersionModel,
    WebhookDeliveryLogModel,
    WebhookSubscriptionModel,
    WhatsAppTemplateModel,
)

__all__ = [
    "TimestampMixin",
    "UUIDMixin",
    "TenantMixin",
    # Public
    "FeedbackModel",
    "StoreOnboardingModel",
    "TenantModel",
    "UserModel",
    "WaitlistModel",
    "AuditLogModel",
    # Omnichannel
    "ChannelConnectionModel",
    "MessageThreadModel",
    "ChannelMessageModel",
    "WhatsAppTemplateModel",
    "CatalogMappingModel",
    "WebhookEventModel",
    "CapiEventModel",
    # Tenant-scoped
    "AutomationLogModel",
    "AutomationRuleModel",
    "StoreModel",
    "ProductModel",
    "CategoryModel",
    "CouponModel",
    "CustomerModel",
    "CustomerAddressModel",
    "InvoiceModel",
    "MessageLogModel",
    "NetworkContributionLogModel",
    "NetworkReputationModel",
    "InstapayIntentModel",
    "OrderModel",
    "PageViewModel",
    "PaymentLinkSessionModel",
    "PaymentProofModel",
    "PaymentTransactionModel",
    "RefundModel",
    "ShipmentModel",
    "RiskAssessmentModel",
    "ShopifyAppSettingsModel",
    "ShopifyInstallationModel",
    "SocialConnectionModel",
    "SocialPostModel",
    "WebhookSubscriptionModel",
    "WebhookDeliveryLogModel",
    "ThemeModel",
    "ThemeVersionModel",
    "StoreThemeModel",
    "ThemeAssetModel",
]
