"""API dependencies module."""

from src.api.dependencies.auth import (
    get_current_store,
    get_current_user_id,
    get_current_user_role,
    require_admin,
    require_admin_2fa,
    require_roles,
    require_store_owner,
    verify_store_ownership,
)
from src.api.dependencies.database import get_db
from src.api.dependencies.email_templates import (
    get_create_email_template_use_case,
    get_default_template_use_case,
    get_delete_email_template_use_case,
    get_get_email_template_use_case,
    get_list_email_templates_use_case,
    get_send_test_email_use_case,
    get_update_email_template_use_case,
)
from src.api.dependencies.fieldsets import (
    PRODUCT_DETAIL_FIELDS,
    PRODUCT_FIELDSET_CONFIG,
    FieldSelector,
    FieldsetConfig,
    get_product_field_selector,
)
from src.api.dependencies.pagination import (
    CursorEncoder,
    CursorParams,
    build_cursor_response,
    get_cursor_params,
    get_cursor_values,
)
from src.api.dependencies.repositories import (
    get_abandoned_checkout_repository,
    get_category_repository,
    get_coupon_repository,
    get_customer_address_repository,
    get_customer_repository,
    get_email_log_repository,
    get_email_template_repository,
    get_feedback_repository,
    get_onboarding_repository,
    get_order_activity_repository,
    get_order_repository,
    get_product_bundle_repository,
    get_product_repository,
    get_product_review_repository,
    get_refund_repository,
    get_shipment_repository,
    get_store_repository,
    get_upsell_rule_repository,
    get_user_repository,
    get_waitlist_repository,
    get_webhook_delivery_log_repository,
    get_webhook_subscription_repository,
)
from src.api.dependencies.services import (
    get_ai_service,
    get_email_service,
    get_email_template_renderer,
    get_image_pipeline,
    get_password_service,
    get_payment_service,
    get_product_cache_service,
    get_storage_service,
    get_token_service,
)

__all__ = [
    # Database
    "get_db",
    # Auth
    "get_current_store",
    "get_current_user_id",
    "get_current_user_role",
    "require_roles",
    "require_store_owner",
    "require_admin",
    "require_admin_2fa",
    "verify_store_ownership",
    # Repositories
    "get_abandoned_checkout_repository",
    "get_category_repository",
    "get_coupon_repository",
    "get_email_log_repository",
    "get_email_template_repository",
    "get_user_repository",
    "get_store_repository",
    "get_product_bundle_repository",
    "get_product_repository",
    "get_product_review_repository",
    "get_customer_repository",
    "get_customer_address_repository",
    "get_feedback_repository",
    "get_onboarding_repository",
    "get_order_activity_repository",
    "get_order_repository",
    "get_refund_repository",
    "get_shipment_repository",
    "get_upsell_rule_repository",
    "get_waitlist_repository",
    "get_webhook_subscription_repository",
    "get_webhook_delivery_log_repository",
    # Services
    "get_password_service",
    "get_token_service",
    "get_email_service",
    "get_email_template_renderer",
    "get_payment_service",
    "get_storage_service",
    "get_ai_service",
    "get_image_pipeline",
    "get_product_cache_service",
    # Email template use cases
    "get_create_email_template_use_case",
    "get_update_email_template_use_case",
    "get_delete_email_template_use_case",
    "get_get_email_template_use_case",
    "get_list_email_templates_use_case",
    "get_default_template_use_case",
    "get_send_test_email_use_case",
    # Pagination
    "CursorEncoder",
    "CursorParams",
    "build_cursor_response",
    "get_cursor_params",
    "get_cursor_values",
    # Fieldsets
    "FieldSelector",
    "FieldsetConfig",
    "PRODUCT_DETAIL_FIELDS",
    "PRODUCT_FIELDSET_CONFIG",
    "get_product_field_selector",
]
